/*
 * Endpoint Agents API
 * Manage ThousandEyes Endpoint Agents using this API.
 *
 * The version of the OpenAPI document: 7.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.thousandeyes.api;

import com.thousandeyes.ApiException;
import com.thousandeyes.api.model.AgentTransferRequest;
import com.thousandeyes.api.model.EndpointAgentBulkTransfer207Response;
import com.thousandeyes.api.model.EndpointAgentBulkTransferRequest;
import com.thousandeyes.api.model.Error;
import com.thousandeyes.api.model.UnauthorizedError;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TransferApi
 */
@Disabled
public class TransferApiTest {

    private final TransferApi api = new TransferApi();

    /**
     * Bulk transfer agents
     *
     * Initiates the transfer of multiple agents between accounts. The following conditions apply:  * The requester must possess &#39;write&#39; permissions for both the &#39;from&#39; and &#39;to&#39; accounts involved in each transfer.  * Multiple transfers may involve a mix of different source and destination accounts. * For each transfer request, the &#39;from&#39; account must match the current account of the respective agent. * Transfers are executed asynchronously. * Progress tracking is not intended, but users can monitor the progress by periodically polling the &#39;get agent&#39; endpoint. * Each transfer request is individually validated and completed; this operation is not atomic, meaning transfers can succeed or fail individually. * The API response provides the status of each transfer request. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void endpointAgentBulkTransferTest() throws ApiException {
        String aid = null;
        EndpointAgentBulkTransferRequest endpointAgentBulkTransferRequest = null;
        EndpointAgentBulkTransfer207Response response = api.endpointAgentBulkTransfer(aid, endpointAgentBulkTransferRequest);
        // TODO: test validations
    }

    /**
     * Transfer endpoint agent
     *
     * Initiates the transfer of an agent from its current account, which must correspond to the provided aid, to the target account.  **Note:** It is essential to ensure that the &#x60;aid&#x60; parameter matches the current account of the agent for this operation to succeed. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void endpointAgentSingleTransferTest() throws ApiException {
        String agentId = null;
        AgentTransferRequest agentTransferRequest = null;
        String aid = null;
        api.endpointAgentSingleTransfer(agentId, agentTransferRequest, aid);
        // TODO: test validations
    }

}
