/*
 * Dashboards API
 * Manage ThousandEyes Dashboards
 *
 * The version of the OpenAPI document: 7.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.thousandeyes.api.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.thousandeyes.api.model.ApiDashboardSnapshotAllOfDashboard;
import com.thousandeyes.api.model.ApiReportSnapshotTimeSpan;
import com.thousandeyes.api.model.ApiWidget;
import com.thousandeyes.api.model.DashboardSnapshotLinksLinks;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ApiDashboardSnapshot
 */
public class ApiDashboardSnapshotTest {
    private final ApiDashboardSnapshot model = new ApiDashboardSnapshot();

    /**
     * Model tests for ApiDashboardSnapshot
     */
    @Test
    public void testApiDashboardSnapshot() {
        // TODO: test ApiDashboardSnapshot
    }

    /**
     * Test the property 'links'
     */
    @Test
    public void linksTest() {
        // TODO: test links
    }

    /**
     * Test the property 'snapshotId'
     */
    @Test
    public void snapshotIdTest() {
        // TODO: test snapshotId
    }

    /**
     * Test the property 'snapshotName'
     */
    @Test
    public void snapshotNameTest() {
        // TODO: test snapshotName
    }

    /**
     * Test the property 'aid'
     */
    @Test
    public void aidTest() {
        // TODO: test aid
    }

    /**
     * Test the property 'isShared'
     */
    @Test
    public void isSharedTest() {
        // TODO: test isShared
    }

    /**
     * Test the property 'snapshotCreatedDate'
     */
    @Test
    public void snapshotCreatedDateTest() {
        // TODO: test snapshotCreatedDate
    }

    /**
     * Test the property 'dashboard'
     */
    @Test
    public void dashboardTest() {
        // TODO: test dashboard
    }

    /**
     * Test the property 'widgets'
     */
    @Test
    public void widgetsTest() {
        // TODO: test widgets
    }

    /**
     * Test the property 'isScheduled'
     */
    @Test
    public void isScheduledTest() {
        // TODO: test isScheduled
    }

    /**
     * Test the property 'timeSpan'
     */
    @Test
    public void timeSpanTest() {
        // TODO: test timeSpan
    }

    /**
     * Test the property 'snapshotExpirationDate'
     */
    @Test
    public void snapshotExpirationDateTest() {
        // TODO: test snapshotExpirationDate
    }

}
