/*
 * Dashboards API
 * Manage ThousandEyes Dashboards.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.thousandeyes.sdk.dashboards.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.thousandeyes.sdk.dashboards.model.DashboardScheduleEndCondition;
import com.thousandeyes.sdk.dashboards.model.DashboardScheduleRepeat;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * Common properties for a dashboard snapshot schedule recurrence.
 */
@JsonPropertyOrder({
  DashboardScheduleCronSpecBase.JSON_PROPERTY_START_TIME,
  DashboardScheduleCronSpecBase.JSON_PROPERTY_ZONE_CODE,
  DashboardScheduleCronSpecBase.JSON_PROPERTY_REPEAT,
  DashboardScheduleCronSpecBase.JSON_PROPERTY_END_REPEAT
})
@jakarta.annotation.Generated(value = "com.thousandeyes.api.codegen.ThousandeyesJavaGenerator")
public class DashboardScheduleCronSpecBase {
  public static final String JSON_PROPERTY_START_TIME = "startTime";
  private Long startTime;

  public static final String JSON_PROPERTY_ZONE_CODE = "zoneCode";
  private String zoneCode;

  public static final String JSON_PROPERTY_REPEAT = "repeat";
  private DashboardScheduleRepeat repeat;

  public static final String JSON_PROPERTY_END_REPEAT = "endRepeat";
  private DashboardScheduleEndCondition endRepeat;

  public DashboardScheduleCronSpecBase() { 
  }

  public DashboardScheduleCronSpecBase startTime(Long startTime) {
    this.startTime = startTime;
    return this;
  }

   /**
   * Schedule start time as a Unix timestamp in seconds.
   * minimum: 0
   * @return startTime
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_START_TIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getStartTime() {
    return startTime;
  }


  @JsonProperty(JSON_PROPERTY_START_TIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStartTime(Long startTime) {
    this.startTime = startTime;
  }


  public DashboardScheduleCronSpecBase zoneCode(String zoneCode) {
    this.zoneCode = zoneCode;
    return this;
  }

   /**
   * An IANA time zone identifier used to interpret &#x60;startTime&#x60; and recurrence. For example, &#x60;America/Los_Angeles&#x60;.
   * @return zoneCode
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ZONE_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getZoneCode() {
    return zoneCode;
  }


  @JsonProperty(JSON_PROPERTY_ZONE_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setZoneCode(String zoneCode) {
    this.zoneCode = zoneCode;
  }


  public DashboardScheduleCronSpecBase repeat(DashboardScheduleRepeat repeat) {
    this.repeat = repeat;
    return this;
  }

   /**
   * Get repeat
   * @return repeat
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_REPEAT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public DashboardScheduleRepeat getRepeat() {
    return repeat;
  }


  @JsonProperty(JSON_PROPERTY_REPEAT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRepeat(DashboardScheduleRepeat repeat) {
    this.repeat = repeat;
  }


  public DashboardScheduleCronSpecBase endRepeat(DashboardScheduleEndCondition endRepeat) {
    this.endRepeat = endRepeat;
    return this;
  }

   /**
   * Get endRepeat
   * @return endRepeat
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_END_REPEAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DashboardScheduleEndCondition getEndRepeat() {
    return endRepeat;
  }


  @JsonProperty(JSON_PROPERTY_END_REPEAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndRepeat(DashboardScheduleEndCondition endRepeat) {
    this.endRepeat = endRepeat;
  }


  /**
   * Return true if this DashboardScheduleCronSpecBase object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DashboardScheduleCronSpecBase dashboardScheduleCronSpecBase = (DashboardScheduleCronSpecBase) o;
    return Objects.equals(this.startTime, dashboardScheduleCronSpecBase.startTime) &&
        Objects.equals(this.zoneCode, dashboardScheduleCronSpecBase.zoneCode) &&
        Objects.equals(this.repeat, dashboardScheduleCronSpecBase.repeat) &&
        Objects.equals(this.endRepeat, dashboardScheduleCronSpecBase.endRepeat);
  }

  @Override
  public int hashCode() {
    return Objects.hash(startTime, zoneCode, repeat, endRepeat);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DashboardScheduleCronSpecBase {\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    zoneCode: ").append(toIndentedString(zoneCode)).append("\n");
    sb.append("    repeat: ").append(toIndentedString(repeat)).append("\n");
    sb.append("    endRepeat: ").append(toIndentedString(endRepeat)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class ModelBuilder {

    private DashboardScheduleCronSpecBase instance;

    public ModelBuilder() {
      this(new DashboardScheduleCronSpecBase());
    }

    protected ModelBuilder(DashboardScheduleCronSpecBase instance) {
      this.instance = instance;
    }

    public DashboardScheduleCronSpecBase.ModelBuilder startTime(Long startTime) {
      this.instance.setStartTime(startTime);
      return this;
    }
    public DashboardScheduleCronSpecBase.ModelBuilder zoneCode(String zoneCode) {
      this.instance.setZoneCode(zoneCode);
      return this;
    }
    public DashboardScheduleCronSpecBase.ModelBuilder repeat(DashboardScheduleRepeat repeat) {
      this.instance.setRepeat(repeat);
      return this;
    }
    public DashboardScheduleCronSpecBase.ModelBuilder endRepeat(DashboardScheduleEndCondition endRepeat) {
      this.instance.setEndRepeat(endRepeat);
      return this;
    }

    /**
     * Returns a built DashboardScheduleCronSpecBase instance.
     *
     * <p>The builder is not reusable.</p>
     */
    public DashboardScheduleCronSpecBase build() {
      try {
        return this.instance;
      } finally {
        // Ensure that this builder cannot mutate an already-built instance.
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
   * Create a builder with no initialized fields.
   */
  public static DashboardScheduleCronSpecBase.ModelBuilder builder() {
    return new DashboardScheduleCronSpecBase.ModelBuilder();
  }

  /**
   * Create a builder with a shallow copy of this instance.
   */
  public DashboardScheduleCronSpecBase.ModelBuilder toBuilder() {
    DashboardScheduleCronSpecBase.ModelBuilder builder = new DashboardScheduleCronSpecBase.ModelBuilder()
      .startTime(getStartTime())
      .zoneCode(getZoneCode())
      .repeat(getRepeat())
      .endRepeat(getEndRepeat());
    return builder;
  }

}

