/*
 * Dashboards API
 * Manage ThousandEyes Dashboards.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.thousandeyes.sdk.dashboards.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Auto-refresh interval for a dashboard. Use &#x60;off&#x60; to disable auto-refresh.
 */
public enum RefreshRate {
  
  OFF("off"),
  
  _2M("2m"),
  
  _5M("5m"),
  
  _10M("10m"),
  
  _15M("15m"),
  
  _30M("30m"),
  
  _60M("60m"),
  
  UNKNOWN("unknown");

  private String value;

  RefreshRate(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static RefreshRate fromValue(String value) {
    for (RefreshRate b : RefreshRate.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    return UNKNOWN;
  }

}

