/*
 * Endpoint Tests API
 *  ## Overview Manage endpoint agent dynamic and scheduled tests using the Endpoint Tests API.
 *
 * The version of the OpenAPI document: 7.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.thousandeyes.api.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.thousandeyes.api.model.EndpointTestAuthType;
import com.thousandeyes.api.model.EndpointTestProtocol;
import com.thousandeyes.api.model.TestProbeMode;
import com.thousandeyes.api.model.TestSslVersionId;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for EndpointHttpServerBaseTest
 */
public class EndpointHttpServerBaseTestTest {
    private final EndpointHttpServerBaseTest model = new EndpointHttpServerBaseTest();

    /**
     * Model tests for EndpointHttpServerBaseTest
     */
    @Test
    public void testEndpointHttpServerBaseTest() {
        // TODO: test EndpointHttpServerBaseTest
    }

    /**
     * Test the property 'authType'
     */
    @Test
    public void authTypeTest() {
        // TODO: test authType
    }

    /**
     * Test the property 'hasPathTraceInSession'
     */
    @Test
    public void hasPathTraceInSessionTest() {
        // TODO: test hasPathTraceInSession
    }

    /**
     * Test the property 'httpTimeLimit'
     */
    @Test
    public void httpTimeLimitTest() {
        // TODO: test httpTimeLimit
    }

    /**
     * Test the property 'protocol'
     */
    @Test
    public void protocolTest() {
        // TODO: test protocol
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'username'
     */
    @Test
    public void usernameTest() {
        // TODO: test username
    }

    /**
     * Test the property 'sslVersionId'
     */
    @Test
    public void sslVersionIdTest() {
        // TODO: test sslVersionId
    }

    /**
     * Test the property 'tcpProbeMode'
     */
    @Test
    public void tcpProbeModeTest() {
        // TODO: test tcpProbeMode
    }

    /**
     * Test the property 'verifyCertificate'
     */
    @Test
    public void verifyCertificateTest() {
        // TODO: test verifyCertificate
    }

}
