import org.apache.tools.ant.filters.ReplaceTokens

plugins {
    id "java-library"
}

repositories {
    maven {
        url teRepoUrl
        credentials {
            username teRepoUser
            password teRepoPassword
        }
    }
}

processResources {
    filter ReplaceTokens, tokens: [
            "version": project.property("version")
    ]
}
