/*
 * Dashboards API
 * Manage ThousandEyes Dashboards
 *
 * The version of the OpenAPI document: 7.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.thousandeyes.api.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * State of the agent.
 */
@JsonAdapter(EnterpriseAgentState.Adapter.class)
public enum EnterpriseAgentState {
  
  ONLINE("online"),
  
  OFFLINE("offline"),
  
  DISABLED("disabled");

  private String value;

  EnterpriseAgentState(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static EnterpriseAgentState fromValue(String value) {
    for (EnterpriseAgentState b : EnterpriseAgentState.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<EnterpriseAgentState> {
    @Override
    public void write(final JsonWriter jsonWriter, final EnterpriseAgentState enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public EnterpriseAgentState read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return EnterpriseAgentState.fromValue(value);
    }
  }
}

