/*
 * Dashboards API
 * Manage ThousandEyes Dashboards
 *
 * The version of the OpenAPI document: 7.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.thousandeyes.api.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Datasource of the stacked area chart widget.
 */
@JsonAdapter(StackedAreaChartDatasource.Adapter.class)
public enum StackedAreaChartDatasource {
  
  CLOUD_AND_ENTERPRISE_AGENTS("CLOUD_AND_ENTERPRISE_AGENTS"),
  
  ENDPOINT_BROWSER_SESSION("ENDPOINT_BROWSER_SESSION"),
  
  ENDPOINT_SCHEDULED_TEST("ENDPOINT_SCHEDULED_TEST");

  private String value;

  StackedAreaChartDatasource(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static StackedAreaChartDatasource fromValue(String value) {
    for (StackedAreaChartDatasource b : StackedAreaChartDatasource.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<StackedAreaChartDatasource> {
    @Override
    public void write(final JsonWriter jsonWriter, final StackedAreaChartDatasource enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public StackedAreaChartDatasource read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return StackedAreaChartDatasource.fromValue(value);
    }
  }
}

