/*
 * BGP Monitors
 *  ## Overview Retrieve information about BGP monitors available for ThousandEyes account.
 *
 * The version of the OpenAPI document: 7.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.thousandeyes.api.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Type of monitor
 */
@JsonAdapter(MonitorType.Adapter.class)
public enum MonitorType {
  
  PUBLIC("public"),
  
  PRIVATE("private");

  private String value;

  MonitorType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static MonitorType fromValue(String value) {
    for (MonitorType b : MonitorType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<MonitorType> {
    @Override
    public void write(final JsonWriter jsonWriter, final MonitorType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public MonitorType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return MonitorType.fromValue(value);
    }
  }
}

