/*
 * Agents API
 *  ## Overview Manage Cloud and Enterprise Agents available to your account in ThousandEyes.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.thousandeyes.sdk.agents.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Type of the agent.
 */
public enum CloudEnterpriseAgentType {
  
  CLOUD("cloud"),
  
  ENTERPRISE_CLUSTER("enterprise-cluster"),
  
  ENTERPRISE("enterprise"),
  
  UNKNOWN("unknown");

  private String value;

  CloudEnterpriseAgentType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static CloudEnterpriseAgentType fromValue(String value) {
    for (CloudEnterpriseAgentType b : CloudEnterpriseAgentType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    return UNKNOWN;
  }

}

