/*
 * Endpoint Tests API
 * Manage endpoint agent dynamic and scheduled tests using the Endpoint Tests API. 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.thousandeyes.sdk.endpoint.tests;

import com.thousandeyes.sdk.endpoint.tests.model.EndpointRealUserTestsResponse;
import com.thousandeyes.sdk.endpoint.tests.model.Error;
import com.thousandeyes.sdk.endpoint.tests.model.UnauthorizedError;
import static com.github.tomakehurst.wiremock.client.WireMock.*;
import static com.github.tomakehurst.wiremock.common.ContentTypes.AUTHORIZATION;
import static com.github.tomakehurst.wiremock.common.ContentTypes.CONTENT_TYPE;
import static com.thousandeyes.sdk.serialization.JSON.getDefault;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import com.fasterxml.jackson.core.JsonProcessingException;

import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.github.tomakehurst.wiremock.junit5.WireMockRuntimeInfo;
import com.github.tomakehurst.wiremock.junit5.WireMockTest;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.thousandeyes.sdk.client.ApiClient;
import com.thousandeyes.sdk.client.ApiException;
import com.thousandeyes.sdk.client.NativeApiClient;


/**
 * Request and Response model deserialization tests for EndpointRealUserTestsApi
 */
@WireMockTest
public class EndpointRealUserTestsApiTest {
    private static final String TOKEN = "valid-token";
    private static final String BEARER_TOKEN = "Bearer %s".formatted(TOKEN);
    private static EndpointRealUserTestsApi api;
    private final ObjectMapper mapper = getDefault()
            .getMapper()
            .configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, true);

    @BeforeAll
    public static void setup(WireMockRuntimeInfo wireMockRuntimeInfo) {
        ApiClient client = NativeApiClient.builder()
                                .baseUri(wireMockRuntimeInfo.getHttpBaseUrl())
                                .bearerToken(TOKEN)
                                .build();
        api = new EndpointRealUserTestsApi(client);
    }
    
    /**
     * List endpoint real user tests
     * <p>
     * Returns real user test domain monitoring profiles for endpoint agents.
     *
     * @throws JsonProcessingException if the deserialization fails
     */
    @Test
    public void getEndpointRealUserTestsRequestAndResponseDeserializationTest()
            throws JsonProcessingException, ApiException
    {


        var responseBodyJson = """
                {
                  "realUserTests" : [ {
                    "includedDomains" : [ "example.com", "example.com" ],
                    "profileId" : "73421",
                    "monitoringSettings" : {
                      "monitoringSettingsId" : "1f5c1b5d-8a0d-4d6b-a3be-56b060f7f2c9",
                      "monitoringSettingsType" : "agent-tags",
                      "tagIds" : [ "49d9e7d2-7df5-43df-9b37-aa596b929062" ],
                      "labelIds" : [ "567" ]
                    },
                    "name" : "Corporate domains",
                    "excludedDomains" : [ "static.example.com", "static.example.com" ],
                    "aid" : "1234"
                  }, {
                    "includedDomains" : [ "example.com", "example.com" ],
                    "profileId" : "73421",
                    "monitoringSettings" : {
                      "monitoringSettingsId" : "1f5c1b5d-8a0d-4d6b-a3be-56b060f7f2c9",
                      "monitoringSettingsType" : "agent-tags",
                      "tagIds" : [ "49d9e7d2-7df5-43df-9b37-aa596b929062" ],
                      "labelIds" : [ "567" ]
                    },
                    "name" : "Corporate domains",
                    "excludedDomains" : [ "static.example.com", "static.example.com" ],
                    "aid" : "1234"
                  } ]
                }
                                  """;
        var statusCode = 200;
        var responseContentType = "application/json";
        EndpointRealUserTestsResponse mappedResponse = 
                mapper.readValue(responseBodyJson, EndpointRealUserTestsResponse.class);
        assertNotNull(mappedResponse);

        var path = "/endpoint/tests/real-user-tests";
        stubFor(get(urlPathTemplate(path))
                        .withHeader(AUTHORIZATION, equalTo(BEARER_TOKEN))
                        .willReturn(aResponse()
                                            .withHeader(CONTENT_TYPE, responseContentType)
                                            .withBody(responseBodyJson)
                                            .withStatus(statusCode)));

        var apiResponse = api.getEndpointRealUserTests(null);
        assertEquals(mappedResponse, apiResponse);
    }
    
}
