/*
 * Alerts API
 *  ## Overview Manage all alerts, alert rules and alert suppression windows.
 *
 * The version of the OpenAPI document: 7.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.thousandeyes.api;

import com.thousandeyes.ApiException;
import com.thousandeyes.api.model.AlertSuppressionWindowRequest;
import com.thousandeyes.api.model.CreateSuppressionWindows201Response;
import com.thousandeyes.api.model.Error;
import com.thousandeyes.api.model.Expand;
import com.thousandeyes.api.model.GetSuppressionWindows200Response;
import java.net.URI;
import com.thousandeyes.api.model.UnauthorizedError;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AlertSuppressionWindowsApi
 */
@Disabled
public class AlertSuppressionWindowsApiTest {

    private final AlertSuppressionWindowsApi api = new AlertSuppressionWindowsApi();

    /**
     * Create alert suppression window
     *
     * Creates a new alert suppression window in ThousandEyes, using the  provided POST data. Only Account Admins can create alert suppression windows.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createSuppressionWindowsTest() throws ApiException {
        AlertSuppressionWindowRequest alertSuppressionWindowRequest = null;
        String aid = null;
        List<Expand> expand = null;
        CreateSuppressionWindows201Response response = api.createSuppressionWindows(alertSuppressionWindowRequest, aid, expand);
        // TODO: test validations
    }

    /**
     * Delete alert suppression window
     *
     * Deletes an alert suppression window.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteSuppressionWindowTest() throws ApiException {
        String windowId = null;
        String aid = null;
        api.deleteSuppressionWindow(windowId, aid);
        // TODO: test validations
    }

    /**
     * Retrieve alert suppression window
     *
     * Returns detailed information about an alert suppression window configured in your account group.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSuppressionWindowDetailsTest() throws ApiException {
        String windowId = null;
        String aid = null;
        List<Expand> expand = null;
        CreateSuppressionWindows201Response response = api.getSuppressionWindowDetails(windowId, aid, expand);
        // TODO: test validations
    }

    /**
     * List alert suppression windows
     *
     * Returns a list of all alert suppression windows configured in your account group.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSuppressionWindowsTest() throws ApiException {
        String aid = null;
        GetSuppressionWindows200Response response = api.getSuppressionWindows(aid);
        // TODO: test validations
    }

    /**
     * Update alert suppression window
     *
     * Updates an alert suppression window in ThousandEyes, using the  provided POST data. Only Account Admins can update alert suppression windows.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateSuppressionWindowTest() throws ApiException {
        String windowId = null;
        AlertSuppressionWindowRequest alertSuppressionWindowRequest = null;
        String aid = null;
        List<Expand> expand = null;
        CreateSuppressionWindows201Response response = api.updateSuppressionWindow(windowId, alertSuppressionWindowRequest, aid, expand);
        // TODO: test validations
    }

}
