/*
 * Instant Tests API
 * The Instant Tests API operations lets you create and run new instant tests. You will need to be an Account Admin.  The response does not include the immediate test results. Use the Test Results endpoints to get test results after creating and executing an instant test. You can find the URLs for these endpoints in the _links section of the test definition that is returned when you create the instant test. 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.thousandeyes.sdk.tests.instant;

import static com.thousandeyes.sdk.client.RequestUtil.parameterToPairs;
import static com.thousandeyes.sdk.client.RequestUtil.urlEncode;

import com.thousandeyes.sdk.client.ApiClient;
import com.thousandeyes.sdk.client.ApiException;
import com.thousandeyes.sdk.client.ApiResponse;
import com.thousandeyes.sdk.utils.Config;
import org.apache.commons.lang3.tuple.Pair;
import org.apache.commons.lang3.reflect.TypeUtils;
import com.thousandeyes.sdk.tests.instant.model.DnsServerInstantTestRequest;
import com.thousandeyes.sdk.tests.instant.model.DnsServerInstantTestResponse;
import com.thousandeyes.sdk.tests.instant.model.Error;
import com.thousandeyes.sdk.tests.instant.model.ExpandInstantTestOptions;
import java.net.URI;
import com.thousandeyes.sdk.tests.instant.model.UnauthorizedError;
import com.thousandeyes.sdk.tests.instant.model.ValidationError;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@jakarta.annotation.Generated(value = "com.thousandeyes.api.codegen.ThousandeyesJavaGenerator")
public class DnsServerInstantTestsApi {
  private final ApiClient apiClient;

  public DnsServerInstantTestsApi(ApiClient apiClient) {
    this.apiClient = apiClient;
  }

  /**
   * Create DNS server instant test
   * Creates and runs a new DNS server instant test.
   * @param request operation parameters (required)
   * @return DnsServerInstantTestResponse
   * @throws ApiException if fails to make API call
   */
  public DnsServerInstantTestResponse createDnsServerInstantTest(CreateDnsServerInstantTestRequest request) throws ApiException {
    ApiResponse<DnsServerInstantTestResponse> response = createDnsServerInstantTestWithHttpInfo(request);
    return response.getData();
  }

  /**
   * Create DNS server instant test
   * Creates and runs a new DNS server instant test.
   * @param request operation parameters (required)
   * @return ApiResponse&lt;DnsServerInstantTestResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<DnsServerInstantTestResponse> createDnsServerInstantTestWithHttpInfo(CreateDnsServerInstantTestRequest request) throws ApiException {
    if (request == null) {
      throw new ApiException(400, "Request must not be null when calling createDnsServerInstantTest");
    }
    createDnsServerInstantTestValidateRequest(request.getDnsServerInstantTestRequest());

    var requestBuilder = createDnsServerInstantTestRequestBuilder(request.getDnsServerInstantTestRequest(), request.getAid(), request.getExpand());

    return apiClient.send(requestBuilder.build(), DnsServerInstantTestResponse.class);
  }

  private void createDnsServerInstantTestValidateRequest(DnsServerInstantTestRequest dnsServerInstantTestRequest) throws ApiException {
      // verify the required parameter 'dnsServerInstantTestRequest' is set
      if (dnsServerInstantTestRequest == null) {
        throw new ApiException(400, "Missing the required parameter 'dnsServerInstantTestRequest' when calling createDnsServerInstantTest");
      }
  }

  private com.thousandeyes.sdk.client.ApiRequest.ApiRequestBuilder createDnsServerInstantTestRequestBuilder(DnsServerInstantTestRequest dnsServerInstantTestRequest, String aid, List<ExpandInstantTestOptions> expand) throws ApiException {
    com.thousandeyes.sdk.client.ApiRequest.ApiRequestBuilder requestBuilder = com.thousandeyes.sdk.client.ApiRequest.builder()
            .method("POST");

    String path = "/tests/dns-server/instant";
    requestBuilder.path(path);

    List<Pair<String, String>> localVarQueryParams = new ArrayList<>();
    localVarQueryParams.addAll(parameterToPairs("aid", aid));
    localVarQueryParams.addAll(parameterToPairs("csv", "expand", expand));

    if (!localVarQueryParams.isEmpty()) {
      requestBuilder.queryParams(localVarQueryParams);
    }

    requestBuilder.header("Content-Type", List.of("application/json"));
    requestBuilder.header("Accept", List.of("application/hal+json, application/json, application/problem+json"));
    requestBuilder.header("User-Agent", List.of(Config.USER_AGENT));
    requestBuilder.requestBody(dnsServerInstantTestRequest);
    return requestBuilder;
  }

  public static final class CreateDnsServerInstantTestRequest {
    private final DnsServerInstantTestRequest dnsServerInstantTestRequest;
    private final String aid;
    private final List<ExpandInstantTestOptions> expand;

    private CreateDnsServerInstantTestRequest(Builder builder) {
      this.dnsServerInstantTestRequest = builder.dnsServerInstantTestRequest;
      this.aid = builder.aid;
      this.expand = builder.expand;
    }
    public DnsServerInstantTestRequest getDnsServerInstantTestRequest() {
      return dnsServerInstantTestRequest;
    }
    public String getAid() {
      return aid;
    }
    public List<ExpandInstantTestOptions> getExpand() {
      return expand;
    }
    public static Builder builder() {
      return new Builder();
    }

    public Builder toBuilder() {
      return builder()
          .dnsServerInstantTestRequest(dnsServerInstantTestRequest)
          .aid(aid)
          .expand(expand);
    }

    public static final class Builder {
      private DnsServerInstantTestRequest dnsServerInstantTestRequest;
      private String aid;
      private List<ExpandInstantTestOptions> expand;

      public Builder dnsServerInstantTestRequest(DnsServerInstantTestRequest dnsServerInstantTestRequest) {
        this.dnsServerInstantTestRequest = dnsServerInstantTestRequest;
        return this;
      }
      public Builder aid(String aid) {
        this.aid = aid;
        return this;
      }
      public Builder expand(List<ExpandInstantTestOptions> expand) {
        this.expand = expand;
        return this;
      }
      public CreateDnsServerInstantTestRequest build() {
        return new CreateDnsServerInstantTestRequest(this);
      }
    }
  }

}
