/*
 * Endpoint Instant Scheduled Tests API
 *  ### Overview  You can create and execute a new endpoint instant scheduled test within ThousandEyes using this API. The test parameters are specified in the `POST` data.  The following applies to the Endpoint Instant Scheduled Tests API:  * To initiate the creation and execution of an instant scheduled test, the user must possess the `Edit endpoint tests` permission.  * Upon successful creation of an instant scheduled test, the API responds with an HTTP/201 CREATED status code and return the test definition. * It's important to note that the response does not include the results of the instant scheduled test. To retrieve test results, users can utilize the Endpoint Test Data endpoints. The URLs for these API test data endpoints are provided within the test definition output when an instant scheduled test is created. 
 *
 * The version of the OpenAPI document: 7.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.thousandeyes.api.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.thousandeyes.api.model.EndpointTestAgentSelectorType;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for EndpointAgentToServerInstantTest
 */
public class EndpointAgentToServerInstantTestTest {
    private final EndpointAgentToServerInstantTest model = new EndpointAgentToServerInstantTest();

    /**
     * Model tests for EndpointAgentToServerInstantTest
     */
    @Test
    public void testEndpointAgentToServerInstantTest() {
        // TODO: test EndpointAgentToServerInstantTest
    }

    /**
     * Test the property 'agentSelectorType'
     */
    @Test
    public void agentSelectorTypeTest() {
        // TODO: test agentSelectorType
    }

    /**
     * Test the property 'agents'
     */
    @Test
    public void agentsTest() {
        // TODO: test agents
    }

    /**
     * Test the property 'hasPing'
     */
    @Test
    public void hasPingTest() {
        // TODO: test hasPing
    }

    /**
     * Test the property 'hasTraceroute'
     */
    @Test
    public void hasTracerouteTest() {
        // TODO: test hasTraceroute
    }

    /**
     * Test the property 'endpointAgentLabels'
     */
    @Test
    public void endpointAgentLabelsTest() {
        // TODO: test endpointAgentLabels
    }

    /**
     * Test the property 'maxMachines'
     */
    @Test
    public void maxMachinesTest() {
        // TODO: test maxMachines
    }

    /**
     * Test the property 'port'
     */
    @Test
    public void portTest() {
        // TODO: test port
    }

    /**
     * Test the property 'testName'
     */
    @Test
    public void testNameTest() {
        // TODO: test testName
    }

    /**
     * Test the property 'serverName'
     */
    @Test
    public void serverNameTest() {
        // TODO: test serverName
    }

}
