/*
 * Instant Tests API
 * The Instant Tests API operations lets you create and run new instant tests. You will need to be an Account Admin.  The response does not include the immediate test results. Use the Test Results endpoints to get test results after creating and executing an instant test. You can find the URLs for these endpoints in the _links section of the test definition that is returned when you create the instant test. 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.thousandeyes.sdk.tests.instant.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * TestAgentResponseProperties
 */
@JsonPropertyOrder({
  TestAgentResponseProperties.JSON_PROPERTY_SOURCE_IP_ADDRESS
})
@jakarta.annotation.Generated(value = "com.thousandeyes.api.codegen.ThousandeyesJavaGenerator")
public class TestAgentResponseProperties {
  public static final String JSON_PROPERTY_SOURCE_IP_ADDRESS = "sourceIpAddress";
  private String sourceIpAddress;

  public TestAgentResponseProperties() { 
  }

  @JsonCreator
  public TestAgentResponseProperties(
    @JsonProperty(JSON_PROPERTY_SOURCE_IP_ADDRESS) String sourceIpAddress
  ) {
  this();
    this.sourceIpAddress = sourceIpAddress;
  }

   /**
   * IP address of the agent interface used as the source for the test. Returned when a source interface is selected.
   * @return sourceIpAddress
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SOURCE_IP_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSourceIpAddress() {
    return sourceIpAddress;
  }




  /**
   * Return true if this TestAgentResponseProperties object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TestAgentResponseProperties testAgentResponseProperties = (TestAgentResponseProperties) o;
    return Objects.equals(this.sourceIpAddress, testAgentResponseProperties.sourceIpAddress);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sourceIpAddress);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TestAgentResponseProperties {\n");
    sb.append("    sourceIpAddress: ").append(toIndentedString(sourceIpAddress)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

