/*
 * Instant Tests API
 * The Instant Tests API operations lets you create and run new instant tests. You will need to be an Account Admin.  The response does not include the immediate test results. Use the Test Results endpoints to get test results after creating and executing an instant test. You can find the URLs for these endpoints in the _links section of the test definition that is returned when you create the instant test. 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.thousandeyes.sdk.tests.instant.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.thousandeyes.sdk.tests.instant.model.AgentInterfaces;
import com.thousandeyes.sdk.tests.instant.model.AgentResponse;
import com.thousandeyes.sdk.tests.instant.model.OAuth;
import com.thousandeyes.sdk.tests.instant.model.SharedWithAccount;
import com.thousandeyes.sdk.tests.instant.model.TestAuthType;
import com.thousandeyes.sdk.tests.instant.model.TestCustomHeaders;
import com.thousandeyes.sdk.tests.instant.model.TestLabel;
import com.thousandeyes.sdk.tests.instant.model.TestLinks;
import com.thousandeyes.sdk.tests.instant.model.TestPageLoadingStrategy;
import com.thousandeyes.sdk.tests.instant.model.TestPathTraceMode;
import com.thousandeyes.sdk.tests.instant.model.TestProbeMode;
import com.thousandeyes.sdk.tests.instant.model.TestProtocol;
import com.thousandeyes.sdk.tests.instant.model.TestSslVersionId;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * WebTransactionInstantTestResponse
 */
@JsonPropertyOrder({
  WebTransactionInstantTestResponse.JSON_PROPERTY_CREATED_BY,
  WebTransactionInstantTestResponse.JSON_PROPERTY_CREATED_DATE,
  WebTransactionInstantTestResponse.JSON_PROPERTY_DESCRIPTION,
  WebTransactionInstantTestResponse.JSON_PROPERTY_LIVE_SHARE,
  WebTransactionInstantTestResponse.JSON_PROPERTY_MODIFIED_BY,
  WebTransactionInstantTestResponse.JSON_PROPERTY_MODIFIED_DATE,
  WebTransactionInstantTestResponse.JSON_PROPERTY_SAVED_EVENT,
  WebTransactionInstantTestResponse.JSON_PROPERTY_TEST_ID,
  WebTransactionInstantTestResponse.JSON_PROPERTY_TEST_NAME,
  WebTransactionInstantTestResponse.JSON_PROPERTY_TYPE,
  WebTransactionInstantTestResponse.JSON_PROPERTY_LINKS,
  WebTransactionInstantTestResponse.JSON_PROPERTY_LABELS,
  WebTransactionInstantTestResponse.JSON_PROPERTY_SHARED_WITH_ACCOUNTS,
  WebTransactionInstantTestResponse.JSON_PROPERTY_AUTH_TYPE,
  WebTransactionInstantTestResponse.JSON_PROPERTY_AGENT_INTERFACES,
  WebTransactionInstantTestResponse.JSON_PROPERTY_BANDWIDTH_MEASUREMENTS,
  WebTransactionInstantTestResponse.JSON_PROPERTY_CLIENT_CERTIFICATE,
  WebTransactionInstantTestResponse.JSON_PROPERTY_CONTENT_REGEX,
  WebTransactionInstantTestResponse.JSON_PROPERTY_CUSTOM_HEADERS,
  WebTransactionInstantTestResponse.JSON_PROPERTY_DESIRED_STATUS_CODE,
  WebTransactionInstantTestResponse.JSON_PROPERTY_DISTRIBUTED_TRACING,
  WebTransactionInstantTestResponse.JSON_PROPERTY_DOWNLOAD_LIMIT,
  WebTransactionInstantTestResponse.JSON_PROPERTY_DNS_OVERRIDE,
  WebTransactionInstantTestResponse.JSON_PROPERTY_HTTP_TARGET_TIME,
  WebTransactionInstantTestResponse.JSON_PROPERTY_HTTP_TIME_LIMIT,
  WebTransactionInstantTestResponse.JSON_PROPERTY_HTTP_VERSION,
  WebTransactionInstantTestResponse.JSON_PROPERTY_INCLUDE_HEADERS,
  WebTransactionInstantTestResponse.JSON_PROPERTY_MTU_MEASUREMENTS,
  WebTransactionInstantTestResponse.JSON_PROPERTY_NETWORK_MEASUREMENTS,
  WebTransactionInstantTestResponse.JSON_PROPERTY_NUM_PATH_TRACES,
  WebTransactionInstantTestResponse.JSON_PROPERTY_O_AUTH,
  WebTransactionInstantTestResponse.JSON_PROPERTY_PASSWORD,
  WebTransactionInstantTestResponse.JSON_PROPERTY_PATH_TRACE_MODE,
  WebTransactionInstantTestResponse.JSON_PROPERTY_PROBE_MODE,
  WebTransactionInstantTestResponse.JSON_PROPERTY_PROTOCOL,
  WebTransactionInstantTestResponse.JSON_PROPERTY_SSL_VERSION,
  WebTransactionInstantTestResponse.JSON_PROPERTY_SSL_VERSION_ID,
  WebTransactionInstantTestResponse.JSON_PROPERTY_URL,
  WebTransactionInstantTestResponse.JSON_PROPERTY_USE_NTLM,
  WebTransactionInstantTestResponse.JSON_PROPERTY_USER_AGENT,
  WebTransactionInstantTestResponse.JSON_PROPERTY_USERNAME,
  WebTransactionInstantTestResponse.JSON_PROPERTY_VERIFY_CERTIFICATE,
  WebTransactionInstantTestResponse.JSON_PROPERTY_ALLOW_UNSAFE_LEGACY_RENEGOTIATION,
  WebTransactionInstantTestResponse.JSON_PROPERTY_FOLLOW_REDIRECTS,
  WebTransactionInstantTestResponse.JSON_PROPERTY_FIXED_PACKET_RATE,
  WebTransactionInstantTestResponse.JSON_PROPERTY_OVERRIDE_AGENT_PROXY,
  WebTransactionInstantTestResponse.JSON_PROPERTY_OVERRIDE_PROXY_ID,
  WebTransactionInstantTestResponse.JSON_PROPERTY_COLLECT_PROXY_NETWORK_DATA,
  WebTransactionInstantTestResponse.JSON_PROPERTY_EMULATED_DEVICE_ID,
  WebTransactionInstantTestResponse.JSON_PROPERTY_TARGET_TIME,
  WebTransactionInstantTestResponse.JSON_PROPERTY_TIME_LIMIT,
  WebTransactionInstantTestResponse.JSON_PROPERTY_TRANSACTION_SCRIPT,
  WebTransactionInstantTestResponse.JSON_PROPERTY_BLOCK_DOMAINS,
  WebTransactionInstantTestResponse.JSON_PROPERTY_DISABLE_SCREENSHOT,
  WebTransactionInstantTestResponse.JSON_PROPERTY_ALLOW_MIC_AND_CAMERA,
  WebTransactionInstantTestResponse.JSON_PROPERTY_ALLOW_GEOLOCATION,
  WebTransactionInstantTestResponse.JSON_PROPERTY_BROWSER_LANGUAGE,
  WebTransactionInstantTestResponse.JSON_PROPERTY_PAGE_LOADING_STRATEGY,
  WebTransactionInstantTestResponse.JSON_PROPERTY_RANDOMIZED_START_TIME,
  WebTransactionInstantTestResponse.JSON_PROPERTY_IDENTIFY_AGENT_TRAFFIC_WITH_USER_AGENT,
  WebTransactionInstantTestResponse.JSON_PROPERTY_CREDENTIALS,
  WebTransactionInstantTestResponse.JSON_PROPERTY_AGENTS
})
@jakarta.annotation.Generated(value = "com.thousandeyes.api.codegen.ThousandeyesJavaGenerator")
public class WebTransactionInstantTestResponse {
  public static final String JSON_PROPERTY_CREATED_BY = "createdBy";
  private String createdBy;

  public static final String JSON_PROPERTY_CREATED_DATE = "createdDate";
  private OffsetDateTime createdDate;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  public static final String JSON_PROPERTY_LIVE_SHARE = "liveShare";
  private Boolean liveShare;

  public static final String JSON_PROPERTY_MODIFIED_BY = "modifiedBy";
  private String modifiedBy;

  public static final String JSON_PROPERTY_MODIFIED_DATE = "modifiedDate";
  private OffsetDateTime modifiedDate;

  public static final String JSON_PROPERTY_SAVED_EVENT = "savedEvent";
  private Boolean savedEvent;

  public static final String JSON_PROPERTY_TEST_ID = "testId";
  private String testId;

  public static final String JSON_PROPERTY_TEST_NAME = "testName";
  private String testName;

  public static final String JSON_PROPERTY_TYPE = "type";
  private String type;

  public static final String JSON_PROPERTY_LINKS = "_links";
  private TestLinks links;

  public static final String JSON_PROPERTY_LABELS = "labels";
  private List<TestLabel> labels = new ArrayList<>();

  public static final String JSON_PROPERTY_SHARED_WITH_ACCOUNTS = "sharedWithAccounts";
  private List<SharedWithAccount> sharedWithAccounts = new ArrayList<>();

  public static final String JSON_PROPERTY_AUTH_TYPE = "authType";
  private TestAuthType authType = TestAuthType.NONE;

  public static final String JSON_PROPERTY_AGENT_INTERFACES = "agentInterfaces";
  private AgentInterfaces agentInterfaces;

  public static final String JSON_PROPERTY_BANDWIDTH_MEASUREMENTS = "bandwidthMeasurements";
  private Boolean bandwidthMeasurements;

  public static final String JSON_PROPERTY_CLIENT_CERTIFICATE = "clientCertificate";
  private String clientCertificate;

  public static final String JSON_PROPERTY_CONTENT_REGEX = "contentRegex";
  private String contentRegex;

  public static final String JSON_PROPERTY_CUSTOM_HEADERS = "customHeaders";
  private TestCustomHeaders customHeaders;

  public static final String JSON_PROPERTY_DESIRED_STATUS_CODE = "desiredStatusCode";
  private String desiredStatusCode = "default";

  public static final String JSON_PROPERTY_DISTRIBUTED_TRACING = "distributedTracing";
  private Boolean distributedTracing;

  public static final String JSON_PROPERTY_DOWNLOAD_LIMIT = "downloadLimit";
  private Integer downloadLimit;

  public static final String JSON_PROPERTY_DNS_OVERRIDE = "dnsOverride";
  private String dnsOverride;

  public static final String JSON_PROPERTY_HTTP_TARGET_TIME = "httpTargetTime";
  private Integer httpTargetTime;

  public static final String JSON_PROPERTY_HTTP_TIME_LIMIT = "httpTimeLimit";
  private Integer httpTimeLimit = 5;

  public static final String JSON_PROPERTY_HTTP_VERSION = "httpVersion";
  private Integer httpVersion = 2;

  public static final String JSON_PROPERTY_INCLUDE_HEADERS = "includeHeaders";
  private Boolean includeHeaders = true;

  public static final String JSON_PROPERTY_MTU_MEASUREMENTS = "mtuMeasurements";
  private Boolean mtuMeasurements;

  public static final String JSON_PROPERTY_NETWORK_MEASUREMENTS = "networkMeasurements";
  private Boolean networkMeasurements = true;

  public static final String JSON_PROPERTY_NUM_PATH_TRACES = "numPathTraces";
  private Integer numPathTraces = 3;

  public static final String JSON_PROPERTY_O_AUTH = "oAuth";
  private OAuth oAuth;

  public static final String JSON_PROPERTY_PASSWORD = "password";
  private String password;

  public static final String JSON_PROPERTY_PATH_TRACE_MODE = "pathTraceMode";
  private TestPathTraceMode pathTraceMode = TestPathTraceMode.CLASSIC;

  public static final String JSON_PROPERTY_PROBE_MODE = "probeMode";
  private TestProbeMode probeMode = TestProbeMode.AUTO;

  public static final String JSON_PROPERTY_PROTOCOL = "protocol";
  private TestProtocol protocol = TestProtocol.TCP;

  public static final String JSON_PROPERTY_SSL_VERSION = "sslVersion";
  private String sslVersion;

  public static final String JSON_PROPERTY_SSL_VERSION_ID = "sslVersionId";
  private TestSslVersionId sslVersionId = TestSslVersionId._0;

  public static final String JSON_PROPERTY_URL = "url";
  private String url;

  public static final String JSON_PROPERTY_USE_NTLM = "useNtlm";
  private Boolean useNtlm;

  public static final String JSON_PROPERTY_USER_AGENT = "userAgent";
  private String userAgent;

  public static final String JSON_PROPERTY_USERNAME = "username";
  private String username;

  public static final String JSON_PROPERTY_VERIFY_CERTIFICATE = "verifyCertificate";
  private Boolean verifyCertificate = false;

  public static final String JSON_PROPERTY_ALLOW_UNSAFE_LEGACY_RENEGOTIATION = "allowUnsafeLegacyRenegotiation";
  private Boolean allowUnsafeLegacyRenegotiation = true;

  public static final String JSON_PROPERTY_FOLLOW_REDIRECTS = "followRedirects";
  private Boolean followRedirects = true;

  public static final String JSON_PROPERTY_FIXED_PACKET_RATE = "fixedPacketRate";
  private Integer fixedPacketRate;

  public static final String JSON_PROPERTY_OVERRIDE_AGENT_PROXY = "overrideAgentProxy";
  private Boolean overrideAgentProxy = false;

  public static final String JSON_PROPERTY_OVERRIDE_PROXY_ID = "overrideProxyId";
  private String overrideProxyId;

  public static final String JSON_PROPERTY_COLLECT_PROXY_NETWORK_DATA = "collectProxyNetworkData";
  private Boolean collectProxyNetworkData = false;

  public static final String JSON_PROPERTY_EMULATED_DEVICE_ID = "emulatedDeviceId";
  private String emulatedDeviceId;

  public static final String JSON_PROPERTY_TARGET_TIME = "targetTime";
  private Integer targetTime = 10;

  public static final String JSON_PROPERTY_TIME_LIMIT = "timeLimit";
  private Integer timeLimit = 30;

  public static final String JSON_PROPERTY_TRANSACTION_SCRIPT = "transactionScript";
  private String transactionScript;

  public static final String JSON_PROPERTY_BLOCK_DOMAINS = "blockDomains";
  private String blockDomains;

  public static final String JSON_PROPERTY_DISABLE_SCREENSHOT = "disableScreenshot";
  private Boolean disableScreenshot = false;

  public static final String JSON_PROPERTY_ALLOW_MIC_AND_CAMERA = "allowMicAndCamera";
  private Boolean allowMicAndCamera = false;

  public static final String JSON_PROPERTY_ALLOW_GEOLOCATION = "allowGeolocation";
  private Boolean allowGeolocation = false;

  public static final String JSON_PROPERTY_BROWSER_LANGUAGE = "browserLanguage";
  private String browserLanguage;

  public static final String JSON_PROPERTY_PAGE_LOADING_STRATEGY = "pageLoadingStrategy";
  private TestPageLoadingStrategy pageLoadingStrategy = TestPageLoadingStrategy.NORMAL;

  public static final String JSON_PROPERTY_RANDOMIZED_START_TIME = "randomizedStartTime";
  private Boolean randomizedStartTime = false;

  public static final String JSON_PROPERTY_IDENTIFY_AGENT_TRAFFIC_WITH_USER_AGENT = "identifyAgentTrafficWithUserAgent";
  private Boolean identifyAgentTrafficWithUserAgent = false;

  public static final String JSON_PROPERTY_CREDENTIALS = "credentials";
  private List<String> credentials = new ArrayList<>();

  public static final String JSON_PROPERTY_AGENTS = "agents";
  private List<AgentResponse> agents = new ArrayList<>();

  public WebTransactionInstantTestResponse() { 
  }

  @JsonCreator
  public WebTransactionInstantTestResponse(
    @JsonProperty(JSON_PROPERTY_CREATED_BY) String createdBy, 
    @JsonProperty(JSON_PROPERTY_CREATED_DATE) OffsetDateTime createdDate, 
    @JsonProperty(JSON_PROPERTY_LIVE_SHARE) Boolean liveShare, 
    @JsonProperty(JSON_PROPERTY_MODIFIED_BY) String modifiedBy, 
    @JsonProperty(JSON_PROPERTY_MODIFIED_DATE) OffsetDateTime modifiedDate, 
    @JsonProperty(JSON_PROPERTY_SAVED_EVENT) Boolean savedEvent, 
    @JsonProperty(JSON_PROPERTY_TEST_ID) String testId, 
    @JsonProperty(JSON_PROPERTY_TYPE) String type, 
    @JsonProperty(JSON_PROPERTY_LABELS) List<TestLabel> labels, 
    @JsonProperty(JSON_PROPERTY_SHARED_WITH_ACCOUNTS) List<SharedWithAccount> sharedWithAccounts, 
    @JsonProperty(JSON_PROPERTY_SSL_VERSION) String sslVersion
  ) {
  this();
    this.createdBy = createdBy;
    this.createdDate = createdDate;
    this.liveShare = liveShare;
    this.modifiedBy = modifiedBy;
    this.modifiedDate = modifiedDate;
    this.savedEvent = savedEvent;
    this.testId = testId;
    this.type = type;
    this.labels = labels;
    this.sharedWithAccounts = sharedWithAccounts;
    this.sslVersion = sslVersion;
  }

   /**
   * User that created the test.
   * @return createdBy
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCreatedBy() {
    return createdBy;
  }




   /**
   * UTC created date (ISO date-time format).
   * @return createdDate
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATED_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getCreatedDate() {
    return createdDate;
  }




  public WebTransactionInstantTestResponse description(String description) {
    this.description = description;
    return this;
  }

   /**
   * A description of the test.
   * @return description
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(String description) {
    this.description = description;
  }


   /**
   * Indicates if the test is shared with the account group.
   * @return liveShare
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LIVE_SHARE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getLiveShare() {
    return liveShare;
  }




   /**
   * User that modified the test.
   * @return modifiedBy
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MODIFIED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getModifiedBy() {
    return modifiedBy;
  }




   /**
   * UTC last modification date (ISO date-time format).
   * @return modifiedDate
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MODIFIED_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getModifiedDate() {
    return modifiedDate;
  }




   /**
   * Indicates if the test is a saved event.  **Note**: **Saved Events** are now called **Private Snapshots** in the user interface. This change does not affect API. 
   * @return savedEvent
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SAVED_EVENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getSavedEvent() {
    return savedEvent;
  }




   /**
   * Each test is assigned an unique ID; this is used to access test information and results from other endpoints.
   * @return testId
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TEST_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTestId() {
    return testId;
  }




  public WebTransactionInstantTestResponse testName(String testName) {
    this.testName = testName;
    return this;
  }

   /**
   * The name of the test. Test name must be unique.
   * @return testName
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TEST_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTestName() {
    return testName;
  }


  @JsonProperty(JSON_PROPERTY_TEST_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTestName(String testName) {
    this.testName = testName;
  }


   /**
   * Get type
   * @return type
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getType() {
    return type;
  }




  public WebTransactionInstantTestResponse links(TestLinks links) {
    this.links = links;
    return this;
  }

   /**
   * Get links
   * @return links
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LINKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TestLinks getLinks() {
    return links;
  }


  @JsonProperty(JSON_PROPERTY_LINKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLinks(TestLinks links) {
    this.links = links;
  }


   /**
   * Labels to which the test is assigned. This field is not returned for Instant Tests.
   * @return labels
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LABELS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<TestLabel> getLabels() {
    return labels;
  }




   /**
   * Get sharedWithAccounts
   * @return sharedWithAccounts
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SHARED_WITH_ACCOUNTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<SharedWithAccount> getSharedWithAccounts() {
    return sharedWithAccounts;
  }




  public WebTransactionInstantTestResponse authType(TestAuthType authType) {
    this.authType = authType;
    return this;
  }

   /**
   * Get authType
   * @return authType
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AUTH_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TestAuthType getAuthType() {
    return authType;
  }


  @JsonProperty(JSON_PROPERTY_AUTH_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAuthType(TestAuthType authType) {
    this.authType = authType;
  }


  public WebTransactionInstantTestResponse agentInterfaces(AgentInterfaces agentInterfaces) {
    this.agentInterfaces = agentInterfaces;
    return this;
  }

   /**
   * Get agentInterfaces
   * @return agentInterfaces
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AGENT_INTERFACES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AgentInterfaces getAgentInterfaces() {
    return agentInterfaces;
  }


  @JsonProperty(JSON_PROPERTY_AGENT_INTERFACES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAgentInterfaces(AgentInterfaces agentInterfaces) {
    this.agentInterfaces = agentInterfaces;
  }


  public WebTransactionInstantTestResponse bandwidthMeasurements(Boolean bandwidthMeasurements) {
    this.bandwidthMeasurements = bandwidthMeasurements;
    return this;
  }

   /**
   * Set to &#x60;true&#x60; to enable bandwidth measurements, only applies to Enterprise agents assigned to the test.
   * @return bandwidthMeasurements
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BANDWIDTH_MEASUREMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getBandwidthMeasurements() {
    return bandwidthMeasurements;
  }


  @JsonProperty(JSON_PROPERTY_BANDWIDTH_MEASUREMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBandwidthMeasurements(Boolean bandwidthMeasurements) {
    this.bandwidthMeasurements = bandwidthMeasurements;
  }


  public WebTransactionInstantTestResponse clientCertificate(String clientCertificate) {
    this.clientCertificate = clientCertificate;
    return this;
  }

   /**
   * String representation (containing newline characters) of client certificate, the private key must be placed first, then the certificate.
   * @return clientCertificate
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CLIENT_CERTIFICATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getClientCertificate() {
    return clientCertificate;
  }


  @JsonProperty(JSON_PROPERTY_CLIENT_CERTIFICATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setClientCertificate(String clientCertificate) {
    this.clientCertificate = clientCertificate;
  }


  public WebTransactionInstantTestResponse contentRegex(String contentRegex) {
    this.contentRegex = contentRegex;
    return this;
  }

   /**
   * Content regex, this field does not require escaping.
   * @return contentRegex
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONTENT_REGEX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getContentRegex() {
    return contentRegex;
  }


  @JsonProperty(JSON_PROPERTY_CONTENT_REGEX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContentRegex(String contentRegex) {
    this.contentRegex = contentRegex;
  }


  public WebTransactionInstantTestResponse customHeaders(TestCustomHeaders customHeaders) {
    this.customHeaders = customHeaders;
    return this;
  }

   /**
   * Get customHeaders
   * @return customHeaders
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CUSTOM_HEADERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TestCustomHeaders getCustomHeaders() {
    return customHeaders;
  }


  @JsonProperty(JSON_PROPERTY_CUSTOM_HEADERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustomHeaders(TestCustomHeaders customHeaders) {
    this.customHeaders = customHeaders;
  }


  public WebTransactionInstantTestResponse desiredStatusCode(String desiredStatusCode) {
    this.desiredStatusCode = desiredStatusCode;
    return this;
  }

   /**
   * Specify the HTTP status code value that indicates a successful response. The default value accepts any 2xx or 3xx status code.
   * @return desiredStatusCode
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESIRED_STATUS_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDesiredStatusCode() {
    return desiredStatusCode;
  }


  @JsonProperty(JSON_PROPERTY_DESIRED_STATUS_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDesiredStatusCode(String desiredStatusCode) {
    this.desiredStatusCode = desiredStatusCode;
  }


  public WebTransactionInstantTestResponse distributedTracing(Boolean distributedTracing) {
    this.distributedTracing = distributedTracing;
    return this;
  }

   /**
   * Adds distributed tracing headers to API requests using B3 and W3C standards.
   * @return distributedTracing
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DISTRIBUTED_TRACING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDistributedTracing() {
    return distributedTracing;
  }


  @JsonProperty(JSON_PROPERTY_DISTRIBUTED_TRACING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDistributedTracing(Boolean distributedTracing) {
    this.distributedTracing = distributedTracing;
  }


  public WebTransactionInstantTestResponse downloadLimit(Integer downloadLimit) {
    this.downloadLimit = downloadLimit;
    return this;
  }

   /**
   * Specifies maximum number of bytes to download from the target object.
   * @return downloadLimit
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DOWNLOAD_LIMIT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getDownloadLimit() {
    return downloadLimit;
  }


  @JsonProperty(JSON_PROPERTY_DOWNLOAD_LIMIT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDownloadLimit(Integer downloadLimit) {
    this.downloadLimit = downloadLimit;
  }


  public WebTransactionInstantTestResponse dnsOverride(String dnsOverride) {
    this.dnsOverride = dnsOverride;
    return this;
  }

   /**
   * IP address to use for DNS override.
   * @return dnsOverride
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DNS_OVERRIDE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDnsOverride() {
    return dnsOverride;
  }


  @JsonProperty(JSON_PROPERTY_DNS_OVERRIDE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDnsOverride(String dnsOverride) {
    this.dnsOverride = dnsOverride;
  }


  public WebTransactionInstantTestResponse httpTargetTime(Integer httpTargetTime) {
    this.httpTargetTime = httpTargetTime;
    return this;
  }

   /**
   * Target time for HTTP server completion, specified in milliseconds.
   * minimum: 100
   * maximum: 5000
   * @return httpTargetTime
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HTTP_TARGET_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getHttpTargetTime() {
    return httpTargetTime;
  }


  @JsonProperty(JSON_PROPERTY_HTTP_TARGET_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHttpTargetTime(Integer httpTargetTime) {
    this.httpTargetTime = httpTargetTime;
  }


  public WebTransactionInstantTestResponse httpTimeLimit(Integer httpTimeLimit) {
    this.httpTimeLimit = httpTimeLimit;
    return this;
  }

   /**
   * HTTP time limit in seconds.
   * minimum: 5
   * maximum: 60
   * @return httpTimeLimit
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HTTP_TIME_LIMIT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getHttpTimeLimit() {
    return httpTimeLimit;
  }


  @JsonProperty(JSON_PROPERTY_HTTP_TIME_LIMIT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHttpTimeLimit(Integer httpTimeLimit) {
    this.httpTimeLimit = httpTimeLimit;
  }


  public WebTransactionInstantTestResponse httpVersion(Integer httpVersion) {
    this.httpVersion = httpVersion;
    return this;
  }

   /**
   * HTTP protocol version. Set to &#39;2&#39; to prefer HTTP/2, or &#39;1&#39; to use only HTTP/1.1.
   * minimum: 1
   * maximum: 2
   * @return httpVersion
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HTTP_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getHttpVersion() {
    return httpVersion;
  }


  @JsonProperty(JSON_PROPERTY_HTTP_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHttpVersion(Integer httpVersion) {
    this.httpVersion = httpVersion;
  }


  public WebTransactionInstantTestResponse includeHeaders(Boolean includeHeaders) {
    this.includeHeaders = includeHeaders;
    return this;
  }

   /**
   * Set to &#x60;true&#x60; to capture response headers for objects loaded by the test.
   * @return includeHeaders
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INCLUDE_HEADERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIncludeHeaders() {
    return includeHeaders;
  }


  @JsonProperty(JSON_PROPERTY_INCLUDE_HEADERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIncludeHeaders(Boolean includeHeaders) {
    this.includeHeaders = includeHeaders;
  }


  public WebTransactionInstantTestResponse mtuMeasurements(Boolean mtuMeasurements) {
    this.mtuMeasurements = mtuMeasurements;
    return this;
  }

   /**
   * Set &#x60;true&#x60; to measure MTU sizes on network from agents to the target.
   * @return mtuMeasurements
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MTU_MEASUREMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getMtuMeasurements() {
    return mtuMeasurements;
  }


  @JsonProperty(JSON_PROPERTY_MTU_MEASUREMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMtuMeasurements(Boolean mtuMeasurements) {
    this.mtuMeasurements = mtuMeasurements;
  }


  public WebTransactionInstantTestResponse networkMeasurements(Boolean networkMeasurements) {
    this.networkMeasurements = networkMeasurements;
    return this;
  }

   /**
   * Enable or disable network measurements. Set to true to enable or false to disable network measurements.
   * @return networkMeasurements
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NETWORK_MEASUREMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getNetworkMeasurements() {
    return networkMeasurements;
  }


  @JsonProperty(JSON_PROPERTY_NETWORK_MEASUREMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNetworkMeasurements(Boolean networkMeasurements) {
    this.networkMeasurements = networkMeasurements;
  }


  public WebTransactionInstantTestResponse numPathTraces(Integer numPathTraces) {
    this.numPathTraces = numPathTraces;
    return this;
  }

   /**
   * Number of path traces executed by the agent.
   * minimum: 1
   * maximum: 10
   * @return numPathTraces
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NUM_PATH_TRACES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getNumPathTraces() {
    return numPathTraces;
  }


  @JsonProperty(JSON_PROPERTY_NUM_PATH_TRACES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNumPathTraces(Integer numPathTraces) {
    this.numPathTraces = numPathTraces;
  }


  public WebTransactionInstantTestResponse oAuth(OAuth oAuth) {
    this.oAuth = oAuth;
    return this;
  }

   /**
   * Get oAuth
   * @return oAuth
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_O_AUTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OAuth getoAuth() {
    return oAuth;
  }


  @JsonProperty(JSON_PROPERTY_O_AUTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setoAuth(OAuth oAuth) {
    this.oAuth = oAuth;
  }


  public WebTransactionInstantTestResponse password(String password) {
    this.password = password;
    return this;
  }

   /**
   * Password for Basic/NTLM authentication.
   * @return password
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PASSWORD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPassword() {
    return password;
  }


  @JsonProperty(JSON_PROPERTY_PASSWORD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPassword(String password) {
    this.password = password;
  }


  public WebTransactionInstantTestResponse pathTraceMode(TestPathTraceMode pathTraceMode) {
    this.pathTraceMode = pathTraceMode;
    return this;
  }

   /**
   * Get pathTraceMode
   * @return pathTraceMode
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PATH_TRACE_MODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TestPathTraceMode getPathTraceMode() {
    return pathTraceMode;
  }


  @JsonProperty(JSON_PROPERTY_PATH_TRACE_MODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPathTraceMode(TestPathTraceMode pathTraceMode) {
    this.pathTraceMode = pathTraceMode;
  }


  public WebTransactionInstantTestResponse probeMode(TestProbeMode probeMode) {
    this.probeMode = probeMode;
    return this;
  }

   /**
   * Get probeMode
   * @return probeMode
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROBE_MODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TestProbeMode getProbeMode() {
    return probeMode;
  }


  @JsonProperty(JSON_PROPERTY_PROBE_MODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProbeMode(TestProbeMode probeMode) {
    this.probeMode = probeMode;
  }


  public WebTransactionInstantTestResponse protocol(TestProtocol protocol) {
    this.protocol = protocol;
    return this;
  }

   /**
   * Get protocol
   * @return protocol
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROTOCOL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TestProtocol getProtocol() {
    return protocol;
  }


  @JsonProperty(JSON_PROPERTY_PROTOCOL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProtocol(TestProtocol protocol) {
    this.protocol = protocol;
  }


   /**
   * Reflects the verbose SSL protocol version used by a test.
   * @return sslVersion
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SSL_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSslVersion() {
    return sslVersion;
  }




  public WebTransactionInstantTestResponse sslVersionId(TestSslVersionId sslVersionId) {
    this.sslVersionId = sslVersionId;
    return this;
  }

   /**
   * Get sslVersionId
   * @return sslVersionId
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SSL_VERSION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TestSslVersionId getSslVersionId() {
    return sslVersionId;
  }


  @JsonProperty(JSON_PROPERTY_SSL_VERSION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSslVersionId(TestSslVersionId sslVersionId) {
    this.sslVersionId = sslVersionId;
  }


  public WebTransactionInstantTestResponse url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Target for the test.
   * @return url
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getUrl() {
    return url;
  }


  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUrl(String url) {
    this.url = url;
  }


  public WebTransactionInstantTestResponse useNtlm(Boolean useNtlm) {
    this.useNtlm = useNtlm;
    return this;
  }

   /**
   * Set to true to use NTLM, false to use Basic Authentication. Requires username and password to be set.
   * @return useNtlm
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USE_NTLM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getUseNtlm() {
    return useNtlm;
  }


  @JsonProperty(JSON_PROPERTY_USE_NTLM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUseNtlm(Boolean useNtlm) {
    this.useNtlm = useNtlm;
  }


  public WebTransactionInstantTestResponse userAgent(String userAgent) {
    this.userAgent = userAgent;
    return this;
  }

   /**
   * User-agent string to be provided during the test.
   * @return userAgent
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USER_AGENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUserAgent() {
    return userAgent;
  }


  @JsonProperty(JSON_PROPERTY_USER_AGENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUserAgent(String userAgent) {
    this.userAgent = userAgent;
  }


  public WebTransactionInstantTestResponse username(String username) {
    this.username = username;
    return this;
  }

   /**
   * Username for Basic/NTLM authentication.
   * @return username
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USERNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUsername() {
    return username;
  }


  @JsonProperty(JSON_PROPERTY_USERNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUsername(String username) {
    this.username = username;
  }


  public WebTransactionInstantTestResponse verifyCertificate(Boolean verifyCertificate) {
    this.verifyCertificate = verifyCertificate;
    return this;
  }

   /**
   * Ignore or acknowledge certificate errors. Set to false to ignore certificate errors.
   * @return verifyCertificate
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VERIFY_CERTIFICATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getVerifyCertificate() {
    return verifyCertificate;
  }


  @JsonProperty(JSON_PROPERTY_VERIFY_CERTIFICATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVerifyCertificate(Boolean verifyCertificate) {
    this.verifyCertificate = verifyCertificate;
  }


  public WebTransactionInstantTestResponse allowUnsafeLegacyRenegotiation(Boolean allowUnsafeLegacyRenegotiation) {
    this.allowUnsafeLegacyRenegotiation = allowUnsafeLegacyRenegotiation;
    return this;
  }

   /**
   * Allows TLS renegotiation with servers not supporting RFC 5746. Default Set to true to allow unsafe legacy renegotiation.
   * @return allowUnsafeLegacyRenegotiation
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ALLOW_UNSAFE_LEGACY_RENEGOTIATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getAllowUnsafeLegacyRenegotiation() {
    return allowUnsafeLegacyRenegotiation;
  }


  @JsonProperty(JSON_PROPERTY_ALLOW_UNSAFE_LEGACY_RENEGOTIATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAllowUnsafeLegacyRenegotiation(Boolean allowUnsafeLegacyRenegotiation) {
    this.allowUnsafeLegacyRenegotiation = allowUnsafeLegacyRenegotiation;
  }


  public WebTransactionInstantTestResponse followRedirects(Boolean followRedirects) {
    this.followRedirects = followRedirects;
    return this;
  }

   /**
   * To disable following HTTP/301 or HTTP/302 redirect directives, set this parameter to &#x60;false&#x60;.
   * @return followRedirects
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FOLLOW_REDIRECTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getFollowRedirects() {
    return followRedirects;
  }


  @JsonProperty(JSON_PROPERTY_FOLLOW_REDIRECTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFollowRedirects(Boolean followRedirects) {
    this.followRedirects = followRedirects;
  }


  public WebTransactionInstantTestResponse fixedPacketRate(Integer fixedPacketRate) {
    this.fixedPacketRate = fixedPacketRate;
    return this;
  }

   /**
   * Sets packets rate sent to measure the network in packets per second.
   * minimum: 0
   * maximum: 100
   * @return fixedPacketRate
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FIXED_PACKET_RATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getFixedPacketRate() {
    return fixedPacketRate;
  }


  @JsonProperty(JSON_PROPERTY_FIXED_PACKET_RATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFixedPacketRate(Integer fixedPacketRate) {
    this.fixedPacketRate = fixedPacketRate;
  }


  public WebTransactionInstantTestResponse overrideAgentProxy(Boolean overrideAgentProxy) {
    this.overrideAgentProxy = overrideAgentProxy;
    return this;
  }

   /**
   * Flag indicating if a proxy other than the default should be used. To override the default proxy for agents, set to &#x60;true&#x60; and specify a value for &#x60;overrideProxyId&#x60;.
   * @return overrideAgentProxy
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OVERRIDE_AGENT_PROXY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getOverrideAgentProxy() {
    return overrideAgentProxy;
  }


  @JsonProperty(JSON_PROPERTY_OVERRIDE_AGENT_PROXY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOverrideAgentProxy(Boolean overrideAgentProxy) {
    this.overrideAgentProxy = overrideAgentProxy;
  }


  public WebTransactionInstantTestResponse overrideProxyId(String overrideProxyId) {
    this.overrideProxyId = overrideProxyId;
    return this;
  }

   /**
   * ID of the proxy to be used if the default proxy is overridden.
   * @return overrideProxyId
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OVERRIDE_PROXY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOverrideProxyId() {
    return overrideProxyId;
  }


  @JsonProperty(JSON_PROPERTY_OVERRIDE_PROXY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOverrideProxyId(String overrideProxyId) {
    this.overrideProxyId = overrideProxyId;
  }


  public WebTransactionInstantTestResponse collectProxyNetworkData(Boolean collectProxyNetworkData) {
    this.collectProxyNetworkData = collectProxyNetworkData;
    return this;
  }

   /**
   * Indicates whether network data to the proxy should be collected.
   * @return collectProxyNetworkData
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COLLECT_PROXY_NETWORK_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCollectProxyNetworkData() {
    return collectProxyNetworkData;
  }


  @JsonProperty(JSON_PROPERTY_COLLECT_PROXY_NETWORK_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCollectProxyNetworkData(Boolean collectProxyNetworkData) {
    this.collectProxyNetworkData = collectProxyNetworkData;
  }


  public WebTransactionInstantTestResponse emulatedDeviceId(String emulatedDeviceId) {
    this.emulatedDeviceId = emulatedDeviceId;
    return this;
  }

   /**
   * ID of the emulated device, if specified when the test was created.
   * @return emulatedDeviceId
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EMULATED_DEVICE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEmulatedDeviceId() {
    return emulatedDeviceId;
  }


  @JsonProperty(JSON_PROPERTY_EMULATED_DEVICE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEmulatedDeviceId(String emulatedDeviceId) {
    this.emulatedDeviceId = emulatedDeviceId;
  }


  public WebTransactionInstantTestResponse targetTime(Integer targetTime) {
    this.targetTime = targetTime;
    return this;
  }

   /**
   * Target completion time, in seconds. Defaults to 10. Cannot exceed the &#x60;timeLimit&#x60; value.
   * minimum: 0
   * maximum: 180
   * @return targetTime
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TARGET_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTargetTime() {
    return targetTime;
  }


  @JsonProperty(JSON_PROPERTY_TARGET_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTargetTime(Integer targetTime) {
    this.targetTime = targetTime;
  }


  public WebTransactionInstantTestResponse timeLimit(Integer timeLimit) {
    this.timeLimit = timeLimit;
    return this;
  }

   /**
   * Time limit for transaction in seconds.
   * minimum: 5
   * maximum: 180
   * @return timeLimit
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TIME_LIMIT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTimeLimit() {
    return timeLimit;
  }


  @JsonProperty(JSON_PROPERTY_TIME_LIMIT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimeLimit(Integer timeLimit) {
    this.timeLimit = timeLimit;
  }


  public WebTransactionInstantTestResponse transactionScript(String transactionScript) {
    this.transactionScript = transactionScript;
    return this;
  }

   /**
   * JavaScript of a web transaction test. Quotes must be escaped (precede \&quot; characters with \\ ).
   * @return transactionScript
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TRANSACTION_SCRIPT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getTransactionScript() {
    return transactionScript;
  }


  @JsonProperty(JSON_PROPERTY_TRANSACTION_SCRIPT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTransactionScript(String transactionScript) {
    this.transactionScript = transactionScript;
  }


  public WebTransactionInstantTestResponse blockDomains(String blockDomains) {
    this.blockDomains = blockDomains;
    return this;
  }

   /**
   * Domains or full object URLs to be excluded from metrics and waterfall data for transaction tests.
   * @return blockDomains
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BLOCK_DOMAINS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBlockDomains() {
    return blockDomains;
  }


  @JsonProperty(JSON_PROPERTY_BLOCK_DOMAINS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBlockDomains(String blockDomains) {
    this.blockDomains = blockDomains;
  }


  public WebTransactionInstantTestResponse disableScreenshot(Boolean disableScreenshot) {
    this.disableScreenshot = disableScreenshot;
    return this;
  }

   /**
   * Enables or disables screenshots on error. Set true to not capture
   * @return disableScreenshot
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DISABLE_SCREENSHOT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDisableScreenshot() {
    return disableScreenshot;
  }


  @JsonProperty(JSON_PROPERTY_DISABLE_SCREENSHOT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDisableScreenshot(Boolean disableScreenshot) {
    this.disableScreenshot = disableScreenshot;
  }


  public WebTransactionInstantTestResponse allowMicAndCamera(Boolean allowMicAndCamera) {
    this.allowMicAndCamera = allowMicAndCamera;
    return this;
  }

   /**
   * Set true allow the use of a fake mic and camera in the browser.
   * @return allowMicAndCamera
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ALLOW_MIC_AND_CAMERA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getAllowMicAndCamera() {
    return allowMicAndCamera;
  }


  @JsonProperty(JSON_PROPERTY_ALLOW_MIC_AND_CAMERA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAllowMicAndCamera(Boolean allowMicAndCamera) {
    this.allowMicAndCamera = allowMicAndCamera;
  }


  public WebTransactionInstantTestResponse allowGeolocation(Boolean allowGeolocation) {
    this.allowGeolocation = allowGeolocation;
    return this;
  }

   /**
   * Set true to use the agent’s geolocation by the web page.
   * @return allowGeolocation
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ALLOW_GEOLOCATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getAllowGeolocation() {
    return allowGeolocation;
  }


  @JsonProperty(JSON_PROPERTY_ALLOW_GEOLOCATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAllowGeolocation(Boolean allowGeolocation) {
    this.allowGeolocation = allowGeolocation;
  }


  public WebTransactionInstantTestResponse browserLanguage(String browserLanguage) {
    this.browserLanguage = browserLanguage;
    return this;
  }

   /**
   * Set one of the available browser language that you want to use to configure the browser.
   * @return browserLanguage
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BROWSER_LANGUAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBrowserLanguage() {
    return browserLanguage;
  }


  @JsonProperty(JSON_PROPERTY_BROWSER_LANGUAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBrowserLanguage(String browserLanguage) {
    this.browserLanguage = browserLanguage;
  }


  public WebTransactionInstantTestResponse pageLoadingStrategy(TestPageLoadingStrategy pageLoadingStrategy) {
    this.pageLoadingStrategy = pageLoadingStrategy;
    return this;
  }

   /**
   * Get pageLoadingStrategy
   * @return pageLoadingStrategy
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAGE_LOADING_STRATEGY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TestPageLoadingStrategy getPageLoadingStrategy() {
    return pageLoadingStrategy;
  }


  @JsonProperty(JSON_PROPERTY_PAGE_LOADING_STRATEGY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPageLoadingStrategy(TestPageLoadingStrategy pageLoadingStrategy) {
    this.pageLoadingStrategy = pageLoadingStrategy;
  }


  public WebTransactionInstantTestResponse randomizedStartTime(Boolean randomizedStartTime) {
    this.randomizedStartTime = randomizedStartTime;
    return this;
  }

   /**
   * Indicates whether agents should randomize the start time in each test round.
   * @return randomizedStartTime
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RANDOMIZED_START_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getRandomizedStartTime() {
    return randomizedStartTime;
  }


  @JsonProperty(JSON_PROPERTY_RANDOMIZED_START_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRandomizedStartTime(Boolean randomizedStartTime) {
    this.randomizedStartTime = randomizedStartTime;
  }


  public WebTransactionInstantTestResponse identifyAgentTrafficWithUserAgent(Boolean identifyAgentTrafficWithUserAgent) {
    this.identifyAgentTrafficWithUserAgent = identifyAgentTrafficWithUserAgent;
    return this;
  }

   /**
   * Determines how agent traffic is identified:  * &#x60;false&#x60;: Adds the &#x60;x-thousandeyes-agent: yes&#x60; header. * &#x60;true&#x60;: Appends &#x60;(ThousandEyes Agent)&#x60; to the &#x60;user-agent&#x60; header.  For more information, see [Notes on Agent ID Strategy](https://docs.thousandeyes.com/product-documentation/browser-synthetics/test-settings-page-load-transaction#notes-on-agent-id-strategy). 
   * @return identifyAgentTrafficWithUserAgent
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IDENTIFY_AGENT_TRAFFIC_WITH_USER_AGENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIdentifyAgentTrafficWithUserAgent() {
    return identifyAgentTrafficWithUserAgent;
  }


  @JsonProperty(JSON_PROPERTY_IDENTIFY_AGENT_TRAFFIC_WITH_USER_AGENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIdentifyAgentTrafficWithUserAgent(Boolean identifyAgentTrafficWithUserAgent) {
    this.identifyAgentTrafficWithUserAgent = identifyAgentTrafficWithUserAgent;
  }


  public WebTransactionInstantTestResponse credentials(List<String> credentials) {
    this.credentials = credentials;
    return this;
  }

  public WebTransactionInstantTestResponse addCredentialsItem(String credentialsItem) {
    if (this.credentials == null) {
      this.credentials = new ArrayList<>();
    }
    this.credentials.add(credentialsItem);
    return this;
  }

   /**
   * Contains a list of credential IDs (get &#x60;credentialId&#x60; from &#x60;/credentials&#x60; endpoint).
   * @return credentials
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREDENTIALS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getCredentials() {
    return credentials;
  }


  @JsonProperty(JSON_PROPERTY_CREDENTIALS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCredentials(List<String> credentials) {
    this.credentials = credentials;
  }


  public WebTransactionInstantTestResponse agents(List<AgentResponse> agents) {
    this.agents = agents;
    return this;
  }

  public WebTransactionInstantTestResponse addAgentsItem(AgentResponse agentsItem) {
    if (this.agents == null) {
      this.agents = new ArrayList<>();
    }
    this.agents.add(agentsItem);
    return this;
  }

   /**
   * Contains list of agents.
   * @return agents
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AGENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<AgentResponse> getAgents() {
    return agents;
  }


  @JsonProperty(JSON_PROPERTY_AGENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAgents(List<AgentResponse> agents) {
    this.agents = agents;
  }


  /**
   * Return true if this WebTransactionInstantTestResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebTransactionInstantTestResponse webTransactionInstantTestResponse = (WebTransactionInstantTestResponse) o;
    return Objects.equals(this.createdBy, webTransactionInstantTestResponse.createdBy) &&
        Objects.equals(this.createdDate, webTransactionInstantTestResponse.createdDate) &&
        Objects.equals(this.description, webTransactionInstantTestResponse.description) &&
        Objects.equals(this.liveShare, webTransactionInstantTestResponse.liveShare) &&
        Objects.equals(this.modifiedBy, webTransactionInstantTestResponse.modifiedBy) &&
        Objects.equals(this.modifiedDate, webTransactionInstantTestResponse.modifiedDate) &&
        Objects.equals(this.savedEvent, webTransactionInstantTestResponse.savedEvent) &&
        Objects.equals(this.testId, webTransactionInstantTestResponse.testId) &&
        Objects.equals(this.testName, webTransactionInstantTestResponse.testName) &&
        Objects.equals(this.type, webTransactionInstantTestResponse.type) &&
        Objects.equals(this.links, webTransactionInstantTestResponse.links) &&
        Objects.equals(this.labels, webTransactionInstantTestResponse.labels) &&
        Objects.equals(this.sharedWithAccounts, webTransactionInstantTestResponse.sharedWithAccounts) &&
        Objects.equals(this.authType, webTransactionInstantTestResponse.authType) &&
        Objects.equals(this.agentInterfaces, webTransactionInstantTestResponse.agentInterfaces) &&
        Objects.equals(this.bandwidthMeasurements, webTransactionInstantTestResponse.bandwidthMeasurements) &&
        Objects.equals(this.clientCertificate, webTransactionInstantTestResponse.clientCertificate) &&
        Objects.equals(this.contentRegex, webTransactionInstantTestResponse.contentRegex) &&
        Objects.equals(this.customHeaders, webTransactionInstantTestResponse.customHeaders) &&
        Objects.equals(this.desiredStatusCode, webTransactionInstantTestResponse.desiredStatusCode) &&
        Objects.equals(this.distributedTracing, webTransactionInstantTestResponse.distributedTracing) &&
        Objects.equals(this.downloadLimit, webTransactionInstantTestResponse.downloadLimit) &&
        Objects.equals(this.dnsOverride, webTransactionInstantTestResponse.dnsOverride) &&
        Objects.equals(this.httpTargetTime, webTransactionInstantTestResponse.httpTargetTime) &&
        Objects.equals(this.httpTimeLimit, webTransactionInstantTestResponse.httpTimeLimit) &&
        Objects.equals(this.httpVersion, webTransactionInstantTestResponse.httpVersion) &&
        Objects.equals(this.includeHeaders, webTransactionInstantTestResponse.includeHeaders) &&
        Objects.equals(this.mtuMeasurements, webTransactionInstantTestResponse.mtuMeasurements) &&
        Objects.equals(this.networkMeasurements, webTransactionInstantTestResponse.networkMeasurements) &&
        Objects.equals(this.numPathTraces, webTransactionInstantTestResponse.numPathTraces) &&
        Objects.equals(this.oAuth, webTransactionInstantTestResponse.oAuth) &&
        Objects.equals(this.password, webTransactionInstantTestResponse.password) &&
        Objects.equals(this.pathTraceMode, webTransactionInstantTestResponse.pathTraceMode) &&
        Objects.equals(this.probeMode, webTransactionInstantTestResponse.probeMode) &&
        Objects.equals(this.protocol, webTransactionInstantTestResponse.protocol) &&
        Objects.equals(this.sslVersion, webTransactionInstantTestResponse.sslVersion) &&
        Objects.equals(this.sslVersionId, webTransactionInstantTestResponse.sslVersionId) &&
        Objects.equals(this.url, webTransactionInstantTestResponse.url) &&
        Objects.equals(this.useNtlm, webTransactionInstantTestResponse.useNtlm) &&
        Objects.equals(this.userAgent, webTransactionInstantTestResponse.userAgent) &&
        Objects.equals(this.username, webTransactionInstantTestResponse.username) &&
        Objects.equals(this.verifyCertificate, webTransactionInstantTestResponse.verifyCertificate) &&
        Objects.equals(this.allowUnsafeLegacyRenegotiation, webTransactionInstantTestResponse.allowUnsafeLegacyRenegotiation) &&
        Objects.equals(this.followRedirects, webTransactionInstantTestResponse.followRedirects) &&
        Objects.equals(this.fixedPacketRate, webTransactionInstantTestResponse.fixedPacketRate) &&
        Objects.equals(this.overrideAgentProxy, webTransactionInstantTestResponse.overrideAgentProxy) &&
        Objects.equals(this.overrideProxyId, webTransactionInstantTestResponse.overrideProxyId) &&
        Objects.equals(this.collectProxyNetworkData, webTransactionInstantTestResponse.collectProxyNetworkData) &&
        Objects.equals(this.emulatedDeviceId, webTransactionInstantTestResponse.emulatedDeviceId) &&
        Objects.equals(this.targetTime, webTransactionInstantTestResponse.targetTime) &&
        Objects.equals(this.timeLimit, webTransactionInstantTestResponse.timeLimit) &&
        Objects.equals(this.transactionScript, webTransactionInstantTestResponse.transactionScript) &&
        Objects.equals(this.blockDomains, webTransactionInstantTestResponse.blockDomains) &&
        Objects.equals(this.disableScreenshot, webTransactionInstantTestResponse.disableScreenshot) &&
        Objects.equals(this.allowMicAndCamera, webTransactionInstantTestResponse.allowMicAndCamera) &&
        Objects.equals(this.allowGeolocation, webTransactionInstantTestResponse.allowGeolocation) &&
        Objects.equals(this.browserLanguage, webTransactionInstantTestResponse.browserLanguage) &&
        Objects.equals(this.pageLoadingStrategy, webTransactionInstantTestResponse.pageLoadingStrategy) &&
        Objects.equals(this.randomizedStartTime, webTransactionInstantTestResponse.randomizedStartTime) &&
        Objects.equals(this.identifyAgentTrafficWithUserAgent, webTransactionInstantTestResponse.identifyAgentTrafficWithUserAgent) &&
        Objects.equals(this.credentials, webTransactionInstantTestResponse.credentials) &&
        Objects.equals(this.agents, webTransactionInstantTestResponse.agents);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createdBy, createdDate, description, liveShare, modifiedBy, modifiedDate, savedEvent, testId, testName, type, links, labels, sharedWithAccounts, authType, agentInterfaces, bandwidthMeasurements, clientCertificate, contentRegex, customHeaders, desiredStatusCode, distributedTracing, downloadLimit, dnsOverride, httpTargetTime, httpTimeLimit, httpVersion, includeHeaders, mtuMeasurements, networkMeasurements, numPathTraces, oAuth, password, pathTraceMode, probeMode, protocol, sslVersion, sslVersionId, url, useNtlm, userAgent, username, verifyCertificate, allowUnsafeLegacyRenegotiation, followRedirects, fixedPacketRate, overrideAgentProxy, overrideProxyId, collectProxyNetworkData, emulatedDeviceId, targetTime, timeLimit, transactionScript, blockDomains, disableScreenshot, allowMicAndCamera, allowGeolocation, browserLanguage, pageLoadingStrategy, randomizedStartTime, identifyAgentTrafficWithUserAgent, credentials, agents);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebTransactionInstantTestResponse {\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    liveShare: ").append(toIndentedString(liveShare)).append("\n");
    sb.append("    modifiedBy: ").append(toIndentedString(modifiedBy)).append("\n");
    sb.append("    modifiedDate: ").append(toIndentedString(modifiedDate)).append("\n");
    sb.append("    savedEvent: ").append(toIndentedString(savedEvent)).append("\n");
    sb.append("    testId: ").append(toIndentedString(testId)).append("\n");
    sb.append("    testName: ").append(toIndentedString(testName)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    labels: ").append(toIndentedString(labels)).append("\n");
    sb.append("    sharedWithAccounts: ").append(toIndentedString(sharedWithAccounts)).append("\n");
    sb.append("    authType: ").append(toIndentedString(authType)).append("\n");
    sb.append("    agentInterfaces: ").append(toIndentedString(agentInterfaces)).append("\n");
    sb.append("    bandwidthMeasurements: ").append(toIndentedString(bandwidthMeasurements)).append("\n");
    sb.append("    clientCertificate: ").append(toIndentedString(clientCertificate)).append("\n");
    sb.append("    contentRegex: ").append(toIndentedString(contentRegex)).append("\n");
    sb.append("    customHeaders: ").append(toIndentedString(customHeaders)).append("\n");
    sb.append("    desiredStatusCode: ").append(toIndentedString(desiredStatusCode)).append("\n");
    sb.append("    distributedTracing: ").append(toIndentedString(distributedTracing)).append("\n");
    sb.append("    downloadLimit: ").append(toIndentedString(downloadLimit)).append("\n");
    sb.append("    dnsOverride: ").append(toIndentedString(dnsOverride)).append("\n");
    sb.append("    httpTargetTime: ").append(toIndentedString(httpTargetTime)).append("\n");
    sb.append("    httpTimeLimit: ").append(toIndentedString(httpTimeLimit)).append("\n");
    sb.append("    httpVersion: ").append(toIndentedString(httpVersion)).append("\n");
    sb.append("    includeHeaders: ").append(toIndentedString(includeHeaders)).append("\n");
    sb.append("    mtuMeasurements: ").append(toIndentedString(mtuMeasurements)).append("\n");
    sb.append("    networkMeasurements: ").append(toIndentedString(networkMeasurements)).append("\n");
    sb.append("    numPathTraces: ").append(toIndentedString(numPathTraces)).append("\n");
    sb.append("    oAuth: ").append(toIndentedString(oAuth)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    pathTraceMode: ").append(toIndentedString(pathTraceMode)).append("\n");
    sb.append("    probeMode: ").append(toIndentedString(probeMode)).append("\n");
    sb.append("    protocol: ").append(toIndentedString(protocol)).append("\n");
    sb.append("    sslVersion: ").append(toIndentedString(sslVersion)).append("\n");
    sb.append("    sslVersionId: ").append(toIndentedString(sslVersionId)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    useNtlm: ").append(toIndentedString(useNtlm)).append("\n");
    sb.append("    userAgent: ").append(toIndentedString(userAgent)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    verifyCertificate: ").append(toIndentedString(verifyCertificate)).append("\n");
    sb.append("    allowUnsafeLegacyRenegotiation: ").append(toIndentedString(allowUnsafeLegacyRenegotiation)).append("\n");
    sb.append("    followRedirects: ").append(toIndentedString(followRedirects)).append("\n");
    sb.append("    fixedPacketRate: ").append(toIndentedString(fixedPacketRate)).append("\n");
    sb.append("    overrideAgentProxy: ").append(toIndentedString(overrideAgentProxy)).append("\n");
    sb.append("    overrideProxyId: ").append(toIndentedString(overrideProxyId)).append("\n");
    sb.append("    collectProxyNetworkData: ").append(toIndentedString(collectProxyNetworkData)).append("\n");
    sb.append("    emulatedDeviceId: ").append(toIndentedString(emulatedDeviceId)).append("\n");
    sb.append("    targetTime: ").append(toIndentedString(targetTime)).append("\n");
    sb.append("    timeLimit: ").append(toIndentedString(timeLimit)).append("\n");
    sb.append("    transactionScript: ").append(toIndentedString(transactionScript)).append("\n");
    sb.append("    blockDomains: ").append(toIndentedString(blockDomains)).append("\n");
    sb.append("    disableScreenshot: ").append(toIndentedString(disableScreenshot)).append("\n");
    sb.append("    allowMicAndCamera: ").append(toIndentedString(allowMicAndCamera)).append("\n");
    sb.append("    allowGeolocation: ").append(toIndentedString(allowGeolocation)).append("\n");
    sb.append("    browserLanguage: ").append(toIndentedString(browserLanguage)).append("\n");
    sb.append("    pageLoadingStrategy: ").append(toIndentedString(pageLoadingStrategy)).append("\n");
    sb.append("    randomizedStartTime: ").append(toIndentedString(randomizedStartTime)).append("\n");
    sb.append("    identifyAgentTrafficWithUserAgent: ").append(toIndentedString(identifyAgentTrafficWithUserAgent)).append("\n");
    sb.append("    credentials: ").append(toIndentedString(credentials)).append("\n");
    sb.append("    agents: ").append(toIndentedString(agents)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

