/*
 * Instant Tests API
 *  ### Overview The Instant Tests API endpoint lets you create and run new instant tests. You will need to be a regular user or have the following permissions:   * `API Access`   * `View tests`  The response does not include the immediate test results. Use the Test Results endpoints to get test results after creating and executing an instant test. You can find the URLs for these endpoints in the _links section of the test definition that is returned when you create the instant test.
 *
 * The version of the OpenAPI document: 7.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.thousandeyes.api.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.thousandeyes.api.model.InstantTestRequestAgentsInner;
import com.thousandeyes.api.model.SipTestProtocol;
import com.thousandeyes.api.model.TestIpv6Policy;
import com.thousandeyes.api.model.TestPathTraceMode;
import com.thousandeyes.api.model.TestSipCredentials;
import com.thousandeyes.api.model.UnexpandedInstantTestLinks;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SipServerInstantTestRequest
 */
public class SipServerInstantTestRequestTest {
    private final SipServerInstantTestRequest model = new SipServerInstantTestRequest();

    /**
     * Model tests for SipServerInstantTestRequest
     */
    @Test
    public void testSipServerInstantTestRequest() {
        // TODO: test SipServerInstantTestRequest
    }

    /**
     * Test the property 'createdBy'
     */
    @Test
    public void createdByTest() {
        // TODO: test createdBy
    }

    /**
     * Test the property 'createdDate'
     */
    @Test
    public void createdDateTest() {
        // TODO: test createdDate
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'liveShare'
     */
    @Test
    public void liveShareTest() {
        // TODO: test liveShare
    }

    /**
     * Test the property 'modifiedBy'
     */
    @Test
    public void modifiedByTest() {
        // TODO: test modifiedBy
    }

    /**
     * Test the property 'modifiedDate'
     */
    @Test
    public void modifiedDateTest() {
        // TODO: test modifiedDate
    }

    /**
     * Test the property 'savedEvent'
     */
    @Test
    public void savedEventTest() {
        // TODO: test savedEvent
    }

    /**
     * Test the property 'testId'
     */
    @Test
    public void testIdTest() {
        // TODO: test testId
    }

    /**
     * Test the property 'testName'
     */
    @Test
    public void testNameTest() {
        // TODO: test testName
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'links'
     */
    @Test
    public void linksTest() {
        // TODO: test links
    }

    /**
     * Test the property 'labels'
     */
    @Test
    public void labelsTest() {
        // TODO: test labels
    }

    /**
     * Test the property 'sharedWithAccounts'
     */
    @Test
    public void sharedWithAccountsTest() {
        // TODO: test sharedWithAccounts
    }

    /**
     * Test the property 'agents'
     */
    @Test
    public void agentsTest() {
        // TODO: test agents
    }

    /**
     * Test the property 'authUser'
     */
    @Test
    public void authUserTest() {
        // TODO: test authUser
    }

    /**
     * Test the property 'mtuMeasurements'
     */
    @Test
    public void mtuMeasurementsTest() {
        // TODO: test mtuMeasurements
    }

    /**
     * Test the property 'networkMeasurements'
     */
    @Test
    public void networkMeasurementsTest() {
        // TODO: test networkMeasurements
    }

    /**
     * Test the property 'optionsRegex'
     */
    @Test
    public void optionsRegexTest() {
        // TODO: test optionsRegex
    }

    /**
     * Test the property 'password'
     */
    @Test
    public void passwordTest() {
        // TODO: test password
    }

    /**
     * Test the property 'pathTraceMode'
     */
    @Test
    public void pathTraceModeTest() {
        // TODO: test pathTraceMode
    }

    /**
     * Test the property 'port'
     */
    @Test
    public void portTest() {
        // TODO: test port
    }

    /**
     * Test the property 'protocol'
     */
    @Test
    public void protocolTest() {
        // TODO: test protocol
    }

    /**
     * Test the property 'registerEnabled'
     */
    @Test
    public void registerEnabledTest() {
        // TODO: test registerEnabled
    }

    /**
     * Test the property 'sipRegistrar'
     */
    @Test
    public void sipRegistrarTest() {
        // TODO: test sipRegistrar
    }

    /**
     * Test the property 'sipTargetTime'
     */
    @Test
    public void sipTargetTimeTest() {
        // TODO: test sipTargetTime
    }

    /**
     * Test the property 'sipTimeLimit'
     */
    @Test
    public void sipTimeLimitTest() {
        // TODO: test sipTimeLimit
    }

    /**
     * Test the property 'targetSipCredentials'
     */
    @Test
    public void targetSipCredentialsTest() {
        // TODO: test targetSipCredentials
    }

    /**
     * Test the property 'user'
     */
    @Test
    public void userTest() {
        // TODO: test user
    }

    /**
     * Test the property 'fixedPacketRate'
     */
    @Test
    public void fixedPacketRateTest() {
        // TODO: test fixedPacketRate
    }

    /**
     * Test the property 'ipv6Policy'
     */
    @Test
    public void ipv6PolicyTest() {
        // TODO: test ipv6Policy
    }

}
