/*
 * Tests API
 * This API allows you to list, create, edit, and delete Network and Application Synthetics tests. 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.thousandeyes.sdk.tests.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * &#x60;exact&#x60; requires the same agents to meet the threshold in consecutive rounds. &#x60;auto&#x60; is only enabled for CEA and Endpoint Scheduled test rules. The default is &#x60;any&#x60;.
 */
public enum AlertRoundsViolationMode {
  
  EXACT("exact"),
  
  ANY("any"),
  
  AUTO("auto"),
  
  UNKNOWN("unknown");

  private String value;

  AlertRoundsViolationMode(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static AlertRoundsViolationMode fromValue(String value) {
    for (AlertRoundsViolationMode b : AlertRoundsViolationMode.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    return UNKNOWN;
  }

}

