/*
 * Tests API
 * **Note:** The Page Load Tests, API Tests, and Web Transaction Tests APIs are not available for ThousandEyes for Government instance.  This API allows you to list, create, edit, and delete Network and Application Synthetics tests. 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.thousandeyes.sdk.tests.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * ApiRequestVariable
 */
@JsonPropertyOrder({
  ApiRequestVariable.JSON_PROPERTY_NAME,
  ApiRequestVariable.JSON_PROPERTY_VALUE
})
@jakarta.annotation.Generated(value = "com.thousandeyes.api.codegen.ThousandeyesJavaGenerator")
public class ApiRequestVariable {
  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_VALUE = "value";
  private String value;

  public ApiRequestVariable() { 
  }

  public ApiRequestVariable name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Variable name
   * @return name
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(String name) {
    this.name = name;
  }


  public ApiRequestVariable value(String value) {
    this.value = value;
    return this;
  }

   /**
   * The JSON path of data within the Response Body to assign to this variable.
   * @return value
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getValue() {
    return value;
  }


  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValue(String value) {
    this.value = value;
  }


  /**
   * Return true if this ApiRequestVariable object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiRequestVariable apiRequestVariable = (ApiRequestVariable) o;
    return Objects.equals(this.name, apiRequestVariable.name) &&
        Objects.equals(this.value, apiRequestVariable.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, value);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiRequestVariable {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class ModelBuilder {

    private ApiRequestVariable instance;

    public ModelBuilder() {
      this(new ApiRequestVariable());
    }

    protected ModelBuilder(ApiRequestVariable instance) {
      this.instance = instance;
    }

    public ApiRequestVariable.ModelBuilder name(String name) {
      this.instance.setName(name);
      return this;
    }
    public ApiRequestVariable.ModelBuilder value(String value) {
      this.instance.setValue(value);
      return this;
    }

    /**
     * Returns a built ApiRequestVariable instance.
     *
     * <p>The builder is not reusable.</p>
     */
    public ApiRequestVariable build() {
      try {
        return this.instance;
      } finally {
        // Ensure that this builder cannot mutate an already-built instance.
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
   * Create a builder with no initialized fields.
   */
  public static ApiRequestVariable.ModelBuilder builder() {
    return new ApiRequestVariable.ModelBuilder();
  }

  /**
   * Create a builder with a shallow copy of this instance.
   */
  public ApiRequestVariable.ModelBuilder toBuilder() {
    ApiRequestVariable.ModelBuilder builder = new ApiRequestVariable.ModelBuilder()
      .name(getName())
      .value(getValue());
    return builder;
  }

}

