/*
 * Endpoint Agents API
 * **Note:** The Endpoint Agents Transfer APIs are not available for ThousandEyes for Government instance.  Manage ThousandEyes Endpoint Agents using this API.   For more information about Endpoint Agents, see [Endpoint Agents](https://docs.thousandeyes.com/product-documentation/global-vantage-points/endpoint-agents).
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.thousandeyes.sdk.endpoint.agents.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.thousandeyes.sdk.endpoint.agents.model.EndpointOnlineOfflineLogItemType;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * EndpointOnlineOfflineLogItem
 */
@JsonPropertyOrder({
  EndpointOnlineOfflineLogItem.JSON_PROPERTY_LOG_ITEM_TYPE
})
@jakarta.annotation.Generated(value = "com.thousandeyes.api.codegen.ThousandeyesJavaGenerator")
public class EndpointOnlineOfflineLogItem {
  public static final String JSON_PROPERTY_LOG_ITEM_TYPE = "logItemType";
  private EndpointOnlineOfflineLogItemType logItemType;

  public EndpointOnlineOfflineLogItem() { 
  }

  public EndpointOnlineOfflineLogItem logItemType(EndpointOnlineOfflineLogItemType logItemType) {
    this.logItemType = logItemType;
    return this;
  }

   /**
   * Get logItemType
   * @return logItemType
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOG_ITEM_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public EndpointOnlineOfflineLogItemType getLogItemType() {
    return logItemType;
  }


  @JsonProperty(JSON_PROPERTY_LOG_ITEM_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLogItemType(EndpointOnlineOfflineLogItemType logItemType) {
    this.logItemType = logItemType;
  }


  /**
   * Return true if this EndpointOnlineOfflineLogItem object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EndpointOnlineOfflineLogItem endpointOnlineOfflineLogItem = (EndpointOnlineOfflineLogItem) o;
    return Objects.equals(this.logItemType, endpointOnlineOfflineLogItem.logItemType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(logItemType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EndpointOnlineOfflineLogItem {\n");
    sb.append("    logItemType: ").append(toIndentedString(logItemType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

